### ISSUE TITLE
Add full page screenshot option

### ISSUE THREAD

**Issue by sontek** [pytest-dev/pytest-selenium#101]
You can see how this would be done using Pillow:

http://stackoverflow.com/questions/41721734/taking-screenshot-of-full-page-with-selenium-python-chromedriver

**Comment by davehunt** [comment]
That's neat, though I'm not interested in adding Pillow as a dependency. You should be able to add this in a local plugin by extending the data gathered when generating the HTML report. See https://github.com/pytest-dev/pytest-html#extra-content for more details, and here's where pytest-selenium adds details to the report, which you can use as an example: https://github.com/pytest-dev/pytest-selenium/blob/7d7008256a8a53d5dc3f237d130af774ed43771f/pytest_selenium/pytest_selenium.py#L132-L160

**Comment by sontek** [comment]
It doesn't have to be a hard dependency.  Python packaging supports `extras` which are ways to enable extra functionality.  So you could have `pytest-selenium[fullscreen]` that depends on Pillow

**Comment by cauvery** [comment]
Hi @davehunt  I wanted to try the above code. But getting errors on line for _gather_ undefined variable 
```
if 'url' not in exclude: 
                _gather_url(item, report, driver, summary, extra) 
            if 'screenshot' not in exclude: 
                _gather_screenshot(item, report, driver, summary, extra) 
            if 'html' not in exclude: 
                _gather_html(item, report, driver, summary, extra) 
            if 'logs' not in exclude: 
                _gather_logs(item, report, driver, summary, extra) 
```

Please need help in this.

Thank you,
Cauvery.

**Comment by davehunt** [comment]
@cauvery do you have pytest-selenium installed? it's not clear to me what code you're referring to.. the link in the original issue description or my link to the code from the plugin. If you're still having issues with the plugin please could you raise a new issue with the output from `pytest --version`.
