### ISSUE TITLE
--firefox-path gives permission denied error on osx Sierra

### ISSUE THREAD

**Issue by BeyondEvil** [pytest-dev/pytest-selenium#102]
I need to be able to run two versions of firefox to be able to test with both legacy firefox driver and geckodriver.

The versions I'm using are 47.0.2 and latest (as of writing this that is 52.0)

Here's what I've done:

- Installed 47.0.2 via dmg from mozilla.
- Renamed the .app to `Firefox47`
- Installed 52.0 via brew (`brew install Caskroom/cask/firefox`)
- Renamed that .app to `Firefox52`
- Renamed `Firefox47` back to `Firefox`

Running tests with pytest setting `marionette`capa to `false` works fine (I don't have to specify `--firefox-path`)

Running tests with pytest setting `marionette`capa to `true` and setting `--firefox-path` to `/Applications/Firefox52.app/Contents/MacOS/` does not work and errors out with: `WebDriverException: Message: Failed to start browser /Applications/Firefox52.app/Contents/MacOS/: permission denied`

Meta-data:

platform darwin -- Python 2.7.10, pytest-3.0.7, py-1.4.32, pluggy-0.4.0
driver: Firefox
sensitiveurl: .*
metadata: {'Python': '2.7.10', 'Driver': 'Firefox', 'Capabilities': {}, 'Base URL': '', 'Platform': 'Darwin-16.4.0-x86_64-i386-64bit', 'Plugins': {'variables': '1.5.1', 'selenium': '1.9.1', 'xdist': '1.15.0', 'rerunfailures': '2.1.0', 'html': '1.14.2', 'base-url': '1.3.0', 'metadata': '1.3.0'}, 'Packages': {'py': '1.4.32', 'pytest': '3.0.7', 'pluggy': '0.4.0'}}
rootdir: /Users/jimb/dev/repos/main_service, inifile: pytest.ini
plugins: xdist-1.15.0, variables-1.5.1, selenium-1.9.1, rerunfailures-2.1.0, metadata-1.3.0, html-1.14.2, base-url-1.3.0

**Comment by BeyondEvil** [comment]
You're supposed to give the path INCLUDING the actual binary. smh

**Comment by davehunt** [comment]
I think it's a reasonable enhancement request for geckodriver to look for the Firefox binary if the path provided ends with `.app`. I would suggest raising this at https://github.com/jgraham/rust_mozrunner/issues to get feedback, and if you're interested in writing a patch, the relevant code is here: https://github.com/jgraham/rust_mozrunner/blob/3fc6494cffa6f4e6dd97af26465647e843fa24a6/src/runner.rs#L180
