### ISSUE TITLE
Add support for edge

### ISSUE THREAD

**Issue by birdsarah** [pytest-dev/pytest-selenium#103]

**Comment by davehunt** [comment]
This should be pretty easy. As an example, Safari support was added in 75092cb6b0891e76453b2ebf2f9094254aea21a2 with a test in 03cd43e5e647b9e1c03e1d7da191cb6964537e14 and driver path support was added in https://github.com/pytest-dev/pytest-selenium/commit/52c78ac4cb221487d4897e3aef70ce901143be34.

**Comment by birdsarah** [comment]
Am working on it.
