### ISSUE TITLE
Problem reading `--variables` from pytest.ini if `--driver-path` specified

### ISSUE THREAD

**Issue by birdsarah** [pytest-dev/pytest-selenium#105]
Not sure how best to investigate this or if this is even a pytest selenium problem.

On Windows 10.

I have a pytest.ini file

```
[pytest]
addopts = --variables=variables.json
```

If I run the following (with chromedriver available on the path):

    $ py.test --base-url www.google.com --driver Chrome

Then the `variables.json` is picked up correctly. 
   
However, if I run the following:

    $ py.test --base-url www.google.com --driver Chrome --driver-path ..\..\..\WebDrivers\chromedriver.exe

Then `variables.json` is not picked up for the variables option.

Finally though, if I add `--variables variables.json` into the call then it does work:

    $ py.test --base-url www.google.com --driver Chrome --driver-path ..\..\..\WebDrivers\chromedriver.exe --variables variables.json

**Comment by davehunt** [comment]
That sounds more like a pytest issue. Could you paste your pytest header (showing rootdir, inifile, etc). Also, do you get the same when you use `=` for all command line options? I've seen issues when values are paths can confuse the rootdir lookup.

**Comment by birdsarah** [comment]
> Also, do you get the same when you use = for all command line options? I've seen issues when values are paths can confuse the rootdir lookup.

This is it. If I use `=` for all then I don't get the issue. But that shouldn't be necessary. Agree this is not a pytest-selenium issue. You think this should be in main pytest repo?

**Comment by davehunt** [comment]
So there was https://github.com/pytest-dev/pytest/issues/1471, https://github.com/pytest-dev/pytest/issues/1435, https://github.com/pytest-dev/pytest/issues/1594, which were all addressed by https://github.com/pytest-dev/pytest/pull/1621. It seems like there's still an issue when the test paths are omitted, or the last argument is a path (but not a test path). It's possible this would be addressed by https://github.com/pytest-dev/pytest/issues/1642 but that would still require a user to know about that option. There is a note about this [in the documentation](http://docs.pytest.org/en/latest/customize.html#initialization-determining-rootdir-and-inifile), but it's easy to miss.

**Comment by davehunt** [comment]
Closing this, as it's not a plugin issue.
