### ISSUE TITLE
No support for localhost connection on SauceLabs behind Sauce Connect proxy

### ISSUE THREAD

**Issue by jrbenny35** [pytest-dev/pytest-selenium#106]
Running into an issue connecting to a localhost server through sauce labs.

This line:
[https://github.com/pytest-dev/pytest-selenium/blob/master/pytest_selenium/drivers/saucelabs.py#L26](url)

This allows for a connection to an external host but not a local host. 
Is there anything I could do as a work around or would this need to be added in?

**Comment by davehunt** [comment]
You shouldn't need to change the executor URL to use Sauce Connect. See https://docs.travis-ci.com/user/sauce-connect/ for getting this to work with Travis CI. If you're still having issues with pytest-selenium, please reopen with more details.
