### ISSUE TITLE
support for testingbot local tunnel

### ISSUE THREAD

**Issue by micheletest** [pytest-dev/pytest-selenium#107]
For local testing, testingbot provides a tunnel which will relay requests to their grid. This means that the driver executor will be localhost:4445/wd/hub instead of hub.testingbot.com:4444/wd/hub.  See documentation here: https://testingbot.com/support/other/tunnel

Currently pytest-selenium doesn't support this. Would you want to? If so, not sure if you have any ideas on how to accomplish it.

**Comment by davehunt** [comment]
The executor URL is currently hard-coded, here: https://github.com/pytest-dev/pytest-selenium/blob/7d7008256a8a53d5dc3f237d130af774ed43771f/pytest_selenium/drivers/testingbot.py#L23-L25

We could add `--host` and `--port` arguments much like we have with the remote driver, here: https://github.com/pytest-dev/pytest-selenium/blob/7d7008256a8a53d5dc3f237d130af774ed43771f/pytest_selenium/drivers/remote.py#L12-L22

These would default to `hub.testingbot.com` and `4444` to maintain the existing functionality, but this will then allow users to configure them for the local tunnel.

**Comment by BeyondEvil** [comment]
@davehunt @micheletest I'm looking at implementing this, but I'm a bit confused regarding the port.

The hardcoded version does not provide a port (implicit 80?) so I'm not sure how to handle that.

https://github.com/pytest-dev/pytest-selenium/blob/7d7008256a8a53d5dc3f237d130af774ed43771f/pytest_selenium/drivers/testingbot.py#L23-L25

**Comment by BeyondEvil** [comment]
ping @davehunt :)

**Comment by davehunt** [comment]
Sorry for the late response. I would suggest making port 80 explicit and the default. I am also against adding new command line arguments for each provider such as `--testingbot-host`. Instead, we can just use `--host`.

**Comment by davehunt** [comment]
This has been fixed in #120 thanks to @BeyondEvil and will be included in the upcoming release (hopefully this week).
