### ISSUE TITLE
Unable to start browser in remote driver

### ISSUE THREAD

**Issue by rarelam** [pytest-dev/pytest-selenium#114]
Hi,

I have issue to start my browser in remote. I face this issue for quite some times, I am not sure do my issue is same with [Gecko Driver issue](https://github.com/mozilla/geckodriver/issues/684)

I have attached my screenshot
![pytest-selenium 1](https://cloud.githubusercontent.com/assets/1460421/25420403/87a7aec0-2a8a-11e7-8a6e-9adda96441c2.png)

**Comment by BeyondEvil** [comment]
Hi @rarelam! This issue actually lies within selenium and not the plugin. 

Would you mind logging an issue here instead: https://github.com/SeleniumHQ/selenium/issues ?

**Comment by BeyondEvil** [comment]
@davehunt There is however an issue with the plugin that I discovered that is related to the selenium bug reported in this issue. You get the same error regardless what browser you're running.

The reason is that we call the firefox_profile fixture from the driver_kwargs fixture always. Resulting in browser_profile (in selenium) always having a profile and never being None.

Do you want me to do a PR with a suggested fix?

**Comment by davehunt** [comment]
This was raised in https://github.com/SeleniumHQ/selenium/issues/3897 and has been fixed. The next release of the Python client for Selenium will include this fix.

**Comment by davehunt** [comment]
> There is however an issue with the plugin that I discovered that is related to the selenium bug reported in this issue. You get the same error regardless what browser you're running.
>
> The reason is that we call the firefox_profile fixture from the driver_kwargs fixture always. Resulting in browser_profile (in selenium) always having a profile and never being None.
>
> Do you want me to do a PR with a suggested fix?

I do want to change this so that by default no profile is provided, however there are a few related changes I'd like to make and I haven't yet given it the thought it requires. Leave it with me for now, but thanks for the offer.

**Comment by jwhitlock** [comment]
@davehunt what's the commit / PR for that fix? I'm seeing the same issue (https://github.com/mozilla/kuma/pull/4195, ``KeyError: 'moz:firefoxOptions'``) with the docker images for selenium/hub:3.40 and selenium/node-firefox:3.4.0.

**Comment by davehunt** [comment]
@jwhitlock the fix was referenced in the issue, https://github.com/SeleniumHQ/selenium/commit/41d9d32e2147bc4eb1e51204eb933002a28b4e04. There's since been a new client released, which I believe should work now.

**Comment by jwhitlock** [comment]
I tried [selenium 3.4.1](https://pypi.python.org/pypi/selenium/3.4.1), but it just [moves the error](https://ci.us-west.moz.works/view/MDN/job/mdn_multibranch_pipeline/job/upgrade_pytest_1308322/4/console):

```
        if browser_profile:
            if "moz:firefoxOptions" in capabilities:
                capabilities["moz:firefoxOptions"]["profile"] = browser_profile.encoded
            else:
>               capabilities['desiredCapabilities'].update({'firefox_profile': browser_profile.encoded})
E               KeyError: 'desiredCapabilities'
```

https://ci.us-west.moz.works/view/MDN/job/mdn_multibranch_pipeline/job/upgrade_pytest_1308322/4/console

Is this a new bug? If so, which repo should I file against?
