### ISSUE TITLE
How To setting the mobile emulation of userAgent

### ISSUE THREAD

**Issue by Josephmtsai** [pytest-dev/pytest-selenium#115]
mobile_emulation = {
    "deviceMetrics": { "width": 360, "height": 640, "pixelRatio": 3.0 },
    "userAgent": "Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19" }
chrome_options = Options()
chrome_options.add_experimental_option("mobileEmulation", mobile_emulation)

I have tried the capabilities in json format seems not work, could you have any advice? 

Thanks

**Comment by davehunt** [comment]
It's not clear to me from the description what you've tried. You should be able to implement a `capabilities` fixture, create a `Options` object, and augment your capabilities with the values. For convenience, the Firefox driver provides a `firefox_options` fixture. I've raised https://github.com/pytest-dev/pytest-selenium/issues/116 to add a similar fixture for Chrome options.

**Comment by davehunt** [comment]
The `chrome_options` fixture will be available in the next release, which I'm hoping will be this week.

**Comment by Josephmtsai** [comment]
Hi DaveHunt :+1: 

Thanks
I have put the code in my conftest.py


```
@pytest.yield_fixture
def mobileSelenium(request):
    mobile_emulation = {
    "deviceMetrics": { "width": 360, "height": 640, "pixelRatio": 3.0 },
    "userAgent": "Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19" }
    chrome_options = Options() 
    chrome_options.add_experimental_option("mobileEmulation", mobile_emulation)	
    driver = webdriver.Chrome(chrome_options = chrome_options)
    request.node._driver = driver
    yield driver
    driver.quit()

```
so that when i generate the html report that i could use your report of style

**Comment by davehunt** [comment]
@Josephmtsai that code means that you're not using pytest-selenium, but starting a Chrome instance from your own fixture. Did you mean that this solves the problem for you temporarily until the next release of pytest-selenium? If so, you could also do it by implementing a `capabilities` fixture, creating an `Options` object, and calling `to_capabilities` to add the additional capabilities from the options. Or just wait until pytest-selenium 1.10.0 is out and use the `chrome_options` fixture. 😄

**Comment by Josephmtsai** [comment]
@davehunt :+1: 
YES .It temp fix it, anyways thank you

**Comment by davehunt** [comment]
Closing as this is fixed in the upcoming release. Please reopen if you have issues with v1.10.0.
