### ISSUE TITLE
After upgrading to the latest plugin.py under pytest_html, get  config._environment.append(('Driver', config.option.driver))  AttributeError: 'Config' object has no attribute '_environment'

### ISSUE THREAD

**Issue by reemadaga** [pytest-dev/pytest-selenium#119]
Hello,

I am trying to generate html reports in pytest. I get the following error,  config._environment.append(('Driver', config.option.driver)) AttributeError: 'Config' object has no attribute '_environment after upgrading to the latest plugin.py from one of the bug fixes: https://github.com/davehunt/pytest-html/tree/4c81503c69183a06cdb539535dd14df4409dc1be

Not sure why I am getting this error. 

Thanks,
Reema

**Comment by davehunt** [comment]
Can you check that you're using the latest versions of both pytest-selenium and pytest-html? I suspect you have an older version of pytest-html, which used this `_environment` attribute, but the latest version uses pytest-metadata.

**Comment by reemadaga** [comment]
Upgrading both pytest-selenium and pytest-html resolved the issue. Thank you!
