### ISSUE TITLE
Dictionary comprehension breaks compatibility with Python 2.6

### ISSUE THREAD

**Issue by jmakov** [pytest-dev/pytest-selenium#122]
After the version 1.8.0 dictionary comprehension is used in pytest-selenium/pytest-selenium.py. Please consider using alternatives to support previous Python versions.

**Comment by davehunt** [comment]
The last release of Python 2.6 was October 2013, and this project only promises support for Python 2.7 and 3.6. Please consider upgrading your Python version, or forking this repository if you want to adapt it for Python 2.6.
