### ISSUE TITLE
Tests are skipped if pytest-selenium is installed and --base-url is passed on the command line

### ISSUE THREAD

**Issue by Jenselme** [pytest-dev/pytest-selenium#125]
To reproduce:
1. create a new virtualenv
2. `pip install pytest pytest-base-url pytest-selenium`
3. Create a sample test file with for instance:
```python
def test_example(base_url):
    assert base_url is None
```
4. Run the tests with `pytest --base-url 'toto'`
5. Result:
```
platform linux -- Python 3.5.3, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
sensitiveurl: .*
metadata: {'Base URL': 'toto', 'Capabilities': {}, 'Plugins': {'selenium': '1.10.0', 'metadata': '1.5.0', 'base-url': '1.3.0', 'html': '1.14.2', 'variables': '1.6.1'}, 'Driver': None, 'Python': '3.5.3', 'Platform': 'Linux-4.10.15-200.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five', 'Packages': {'pytest': '3.0.7', 'pluggy': '0.4.0', 'py': '1.4.33'}}
baseurl: toto
rootdir: /tmp/pytest, inifile:
plugins: variables-1.6.1, selenium-1.10.0, metadata-1.5.0, html-1.14.2, base-url-1.3.0
collected 1 items 

test_exple.py s
```

**Expected:** tests are run, not skipped.

Tested with:
- pytest 3.0.7
- pytest-selenium 1.10.0, 1.9.1, 1.9.0, 1.8.0
- pytest-base-url 1.3.0, 1.2.0, 1.1.0, 1.0.0
- Python 3.5.3 and 3.6.1

It can also be reproduced if the base URL is specified in `PYTEST_BASE_URL`.

**Comment by BeyondEvil** [comment]
@Jenselme You need to specify either a sensitive url or mark the test as nondestructive. Please see documentation for more information: http://pytest-selenium.readthedocs.io/en/latest/user_guide.html#sensitive-environments

**Comment by davehunt** [comment]
As @BeyondEvil points out this is part of the safety feature, where tests will not be executed against sensitive environments. If you enable additional reporting in pytest for skipped tests by using `-r=s` or `-r=a` then you'll see a message explaining why the tests are skipped.

**Comment by Jenselme** [comment]
Thanks for your quick responses. What I find confusing is that it works without `--base-url`. Maybe the doc could be improved. Proposal:

> To specify a base URL, refer to the documentation for the pytest-base-url plugin. Don't forget to configure the [sensitive envinments](https://pytest-selenium.readthedocs.io/en/latest/user_guide.html#sensitive-environments) or your tests will be skipped.

What do you think?

**Comment by davehunt** [comment]
@Jenselme if there's no base URL then there's no way to determine if the target is sensitive. I'm happy to merge a patch for the documentation. Another thing we could do is add a warning in the pytest console header when a base URL is considered sensitive.
