### ISSUE TITLE
[Question] How to run browser test remotely?

### ISSUE THREAD

**Issue by rarelam** [pytest-dev/pytest-selenium#128]
Hi,

I have updated all the latest pytest library and selenium library. And using selenium node/ server configuration with version 3.4.0 in local pc.  However I have encounter WebDriver exception.

The command I run:

`py.test --driver Remote --capability browserName firefox --html=Results\report.html`

Please guide me how to fix the error. Thank you.
![1](https://user-images.githubusercontent.com/1460421/27217222-948cf80e-52ab-11e7-866c-c44fc4ff710e.png)
[Result log.zip](https://github.com/pytest-dev/pytest-selenium/files/1080071/Result.log.zip)

**Comment by BeyondEvil** [comment]
@rarelam Please see this discussion: https://github.com/SeleniumHQ/selenium/issues/4017

**Comment by rarelam** [comment]
thank you @BeyondEvil . So I need to wait until selenium grid issue is resolved.

**Comment by BeyondEvil** [comment]
@rarelam Or edit the code yourself (like the last commenter on that thread did)

**Comment by davehunt** [comment]
Thanks for the report @rarelam, and for the quick response @BeyondEvil! I encountered this myself whilst giving some training last week. I was able to revert to a previous version of the Selenium client to proceed. Hopefully this will be resolved soon via a new release of the Selenium server.
