### ISSUE TITLE
Support for headless Chrome

### ISSUE THREAD

**Issue by lmr2391** [pytest-dev/pytest-selenium#135]
Is there a possibility to run tests on Chrome in headless mode that I'm missing from the documentation? In standard selenium I can ensure that by: 
```python
options = webdriver.ChromeOptions()
options.add_argument('headless')
driver = webdriver.Chrome(chrome_options=options)
```

I guessed `capabilities` could be the thing I need, so I tried: `pytest --capability headless True`  but that didn't work. By hacking on the source code of pytest-selenium I was able to use Chrome in headless mode - I modified the `chrome_options` fixture:
```python
@pytest.fixture
def chrome_options():
    options = Options()
    options.add_argument('headless')
    return options
```
This might be working for me on my local machine, but it creates a lot of hassle to ensure that in my staging environment....

**Comment by davehunt** [comment]
@lmr2391 you can override any fixture by defining it in your test module or `conftest.py` file. For example, the following `conftest.py` would enable headless for all Chrome instances:

```python
@pytest.fixture
def chrome_options(chrome_options):
    chrome_options.add_argument('headless')
    return chrome_options
```

**Comment by JamieCzuy** [comment]
@lmr2391, @davehunt - I was playing around to find a way to recognize the command line `--capability headless true` option. I am pretty new to pytest fixtures so there may be a better way - but this works.
This is my `conftest.py`:
```python
import pytest

@pytest.fixture
def chrome_options(chrome_options, pytestconfig):
    capabilities = dict(pytestconfig.option.capabilities)
    if 'true' == capabilities.get('headless', 'false').lower():
        chrome_options.add_argument('headless')
    return chrome_options
```

**Comment by davehunt** [comment]
Hmm.. I wonder if we should add a `--headless` argument to pytest-selenium, which passes the appropriate command line argument to Firefox/Chrome. You could do this in your own `conftest.py` with something like:

```python
def pytest_addoption(parser):
    group = parser.getgroup('selenium', 'selenium')
    group._addoption('--headless',
                     action='store_true',
                     help='enable headless mode for supported browsers.')


@pytest.fixture
def firefox_options(firefox_options, pytestconfig):
    if pytestconfig.getoption('headless'):
        firefox_options.add_argument('headless')
    return firefox_options


@pytest.fixture
def chrome_options(chrome_options, pytestconfig):
    if pytestconfig.getoption('headless'):
        chrome_options.add_argument('headless')
    return chrome_options
```

Note that I've not tested the above, and it's written from memory, so it might need some work. If you get that working, I'd be happy to review a pull request that adds this to the plugin.

**Comment by davehunt** [comment]
`set_headless` just [adds the argument](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/options.py#L130) 🤷‍♂️

**Comment by JamieCzuy** [comment]
Ahh ok - so digger a little deeper - Chrome and Firefox handle various headless arguments differently:

These three styles of headless argument are treated a little differently:

* `headless` (No dash)
    * Chrome
        * _options.headless = False
        * Runs in headless mode
    * Firefox:
        * _options.headless = False
        * Does not run in headless mode
* `-headless` (One dash)
    * Chrome
        * _options.headless = False
        * Runs in headless mode
    * Firefox:
        * **_options.headless = True**
        * **Runs in headless mode**
* `--headless` (Two dashes)
    * Chrome
        * **_options.headless = True**
        * **Runs in headless mode**
    * Firefox:
        * _options.headless = False
        * Runs in headless mode

Given this here is my latest conftest.py:
```python
import pytest


def pytest_addoption(parser):
    group = parser.getgroup('selenium', 'selenium')
    group._addoption('--headless',
                     action='store_true',
                     help='enable headless mode for supported browsers.')


@pytest.fixture
def chrome_options(chrome_options, pytestconfig):
    if pytestconfig.getoption('headless'):
        chrome_options.add_argument('--headless')
    return chrome_options


@pytest.fixture
def firefox_options(firefox_options, pytestconfig):
    if pytestconfig.getoption('headless'):
        firefox_options.add_argument('-headless')
    return firefox_options
```

**Comment by davehunt** [comment]
I'm okay with using `set_headless` as this appears to be implemented for both Firefox and Chrome. It also means that if the browser vendors change how headless is set, the Selenium client will need to be updated, and not our plugin. I'd personally prefer that the `Options` classes implemented a `@headless.setter` so we could do `options.headless = True` rather than `options.set_headless(True)`, but that's just a personal annoyance. 😛
