### ISSUE TITLE
Remote Firefox driver passes incorrect capabilities

### ISSUE THREAD

**Issue by jrbenny35** [pytest-dev/pytest-selenium#136]
Using the latest 3.7.0 docker selenium firefox image and pytest-selenium 1.11.1 I get an error that states ```unable to find matching set of capabilities```. 

I removed pytest selenium and followed the remote driver instructions found here: http://selenium-python.readthedocs.io/getting-started.html#using-selenium-with-remote-webdriver and I was able to get the tests to pass again.

I am thinking the remote capabilities that pytest-selenium copies has been outdated, or maybe the selenium has changed the data type.

**Comment by davehunt** [comment]
@jrbenny35 pytest-selenium doens't copy any remote capabilities. You will need to provide these yourself, just like with the official client. It's possible we could improve this, but first we'd need to understand what capabilities you're missing. Can you provide the console log for the Selenium server, which should show the capabilities in the new session request, and we can then identify what's missing.

**Comment by davehunt** [comment]
I've replicated this, and it appears to be related to https://github.com/pytest-dev/pytest-selenium/blob/master/pytest_selenium/drivers/remote.py#L18. I'll continue to investigate.

**Comment by jrbenny35** [comment]
Awesome, thanks for the update!

**Comment by davehunt** [comment]
Should be fixed by https://github.com/pytest-dev/pytest-selenium/commit/34e081b9b7653ce61e58f0009e3de2ca1e8c1ef3 and a new release should be available soon.
