### ISSUE TITLE
Problem with remote-debugging-port

### ISSUE THREAD

**Issue by williamjamir** [pytest-dev/pytest-selenium#138]
Hi,

How can I use the remote-debugging-port with pytest-selenium?

Running with the following command line everthing works fine:
`.\chrome.exe --headless --remote-debugging-port=9222 --disable-gpu http://localhost:5000/`

But when I try to add the following option on chrome_options fixture 
Code:
`
def chrome_options(chrome_options):
    chrome_options.add_argument('headless')
    chrome_options.add_argument('remote-debugging-port=9222')
    chrome_options.add_argument('disable-gpu')
    return chrome_options
`
I receive the following error:

```
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.WebDriverException: Message: chrome not reachable
E         (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.15063 x86_64)
```

Am I doing some wrong configuration?  Or is this a known issue?

**Comment by davehunt** [comment]
@williamjamir can you try with the `--` before each argument:

```python
@pytest.fixture
def chrome_options(chrome_options):
    chrome_options.add_argument('--headless')
    chrome_options.add_argument('--remote-debugging-port=9222')
    chrome_options.add_argument('--disable-gpu')
    return chrome_options
```

**Comment by williamjamir** [comment]
Sorry for the delay @davehunt, I only had access to the computer today.

Using the -- before each argument raises the same exception

**Comment by davehunt** [comment]
It appears that the pytest plugin and Selenium client are working as expected, but there is an issue with chromedriver using and alternate remote debugging port: https://bugs.chromium.org/p/chromedriver/issues/detail?id=878

**Comment by davehunt** [comment]
Closing as this appears to not be related to the plugin.
