### ISSUE TITLE
Correct way to set up a Test Suite

### ISSUE THREAD

**Issue by lcofre** [pytest-dev/pytest-selenium#141]
Hi!

The test suite I am working on is set up this way:
Several .py files testing different sections of the web application
A test_app.py that imports all other .py files
pytest is called on that last file to execute the whole test suite
```
pytest test_app.py --driver Firefox
```

As a result each function ends up opening a new browser window. I was expecting only one instance reused on the whole test suite.

I am experiencing a constant degrading on the app I am testing and I would like to rule out a problem with the test suite setup.

Is this setup the correct way to use pytest-selenium?

I have a few other pytest testsuites where I set up the use of selenium myself, so this is my first time using pytest selenium.

I know this is a pretty general question so I thank you in advance for your kindness.

**Comment by davehunt** [comment]
Thanks for your question @lcofre. The plugin creates a browser instance for each test function. The main reason for this is to prevent browser state from leaking between tests, either causing failures that would be hard to identify, or tests that only pass by chance. This was previously discussed in https://github.com/pytest-dev/pytest-selenium/issues/59, where a potential workaround is suggested. I hope this helps.
