### ISSUE TITLE
Order of remote driver arguments

### ISSUE THREAD

**Issue by micheletest** [pytest-dev/pytest-selenium#142]
I recently updated python packages, including this one, and ran across a potential issue with the remote driver. If I run the pytest command with `--host notlocalhost --driver Remote --port 1234` (just an example) it does not work. If I run the command with `--driver Remote --port 1234 --host notlocalhost` it does work. For the command with the host first, the host seems to become the default `localhost` instead of the provided host `notlocalhost`.

The actual error due to the incorrect host is: `E urllib.error.URLError: <urlopen error [Errno 111] Connection refused>`

I updated pytest-selenium from 1.9.1 to 1.11.2. Using 1.9.1 I did not see this error.

**Comment by davehunt** [comment]
Interesting. It's possible that we need to avoid overwriting the host/port if they've been set in advance of the driver:

https://github.com/pytest-dev/pytest-selenium/blob/52b9b71197994233f6a5d2bca8a221f5c535690b/pytest_selenium/pytest_selenium.py#L292-L293

**Comment by micheletest** [comment]
Yes, I think that would do it - don't do anything if there is already a host or port. Otherwise use the existing logic. 

```        # set the default host and port if not specified already and if specified in the driver module
        if not namespace.host:
            setattr(namespace, 'host', getattr(driver, 'HOST', None))
        if not namespace.port:
            setattr(namespace, 'port', getattr(driver, 'PORT', None))
```
