### ISSUE TITLE
UserGuide on ChromeDriver log-path via driver_args fixture is outdated

### ISSUE THREAD

**Issue by hroemer** [pytest-dev/pytest-selenium#146]
The documentation about the ChromeDriver [`driver_args` fixture](../blob/4c507f8224d56367ff563aeb0aabc140474ba69c/docs/user_guide.rst#id6) in the UserGuide regarding the `--log-path` argument seems outdated. The fixture is called, but the `--log-path` argument is ignored.

There is a separate fixture `driver_log` available, thus it should be documented like so:

```python
@pytest.fixture
def driver_log(tmpdir):
    return str(tmpdir.join('chromedriver.log'))
```
I believe this extends to the other drivers as well, but haven't verified this.

**Comment by davehunt** [comment]
I agree the documentation should be update to remove mention of the log path, however I'm not sure there's but benefit to documenting the `driver_log` fixture, as this would risk users setting this to a path that is not unique for each test. The path is currently set to a unique temporary directory, and is included in the HTML report and test summary.

**Comment by BeyondEvil** [comment]
I think there's a misunderstanding here. The User Guide isn't referring to an existing `driver_args` fixture, but merely giving an **example** of how one could be _implemented_:

"The ChromeDriver supports various command line arguments. These can be passed by **implementing** a driver_args fixture and returning a list of the desired arguments. The following **example** specifies the log file path:" [my emphasis]

The implemented fixture in the plugin looks like this:

https://github.com/pytest-dev/pytest-selenium/blob/master/pytest_selenium/pytest_selenium.py#L103-L106

If the wording can be made better, I'm happy to update the code. @davehunt @hroemer

**Comment by davehunt** [comment]
The `driver_args` fixture is real: https://github.com/pytest-dev/pytest-selenium/blob/master/pytest_selenium/pytest_selenium.py#L103-L106. If used, these arguments get passed to the driver. Of course, you'll need to make sure you pass arguments that the driver supports, and it may be worth updating the documentation to not use the log path as an example now that we take care of this (and can be overridden via the intentionally undocumented `driver_log` fixture).

Looking at the output from `chromedriver --help` perhaps `--log-level=LEVEL` would be a good alternative for the documentation.

**Comment by BeyondEvil** [comment]
Docs have been updated https://github.com/pytest-dev/pytest-selenium/blob/v1.14.0/docs/user_guide.rst#id6

Closing this. Please re-open if you need more information @hroemer
