### ISSUE TITLE
Add driver log to HTML report even if there is no driver instance

### ISSUE THREAD

**Issue by davehunt** [pytest-dev/pytest-selenium#149]
We currently only add the driver log to the HTML report if there is a driver instance, however this means we fail to include the logs when there is an issue actually creating the driver instance.

We should move the following lines from `_gather_logs`:

https://github.com/pytest-dev/pytest-selenium/blob/2c40b5c395162f598ed02e7302d3ed4d71a0873b/pytest_selenium/pytest_selenium.py#L245-L249

To outside the `if driver is not None` in `pytest_runtest_makereport`:

https://github.com/pytest-dev/pytest-selenium/blob/2c40b5c395162f598ed02e7302d3ed4d71a0873b/pytest_selenium/pytest_selenium.py#L186

This should help with diagnosing issues when staring the driver instance, such as in https://github.com/mozilla/FoxPuppet/pull/115

**Comment by davehunt** [comment]
Would you be interested in working on this @jrbenny35?

**Comment by jrbenny35** [comment]
Yeah I'd love to help with this!

**Comment by jrbenny35** [comment]
@davehunt looking through the ```test_report.py``` test I see a lot of the tests for Logs have been commented out. I am guessing I won't need to add a test for this feature?

**Comment by davehunt** [comment]
You might actually be safe to remove those comments @jrbenny35... I think they were due to logging not being included in the WebDriver spec (therefore no logs would be gathered) but the driver log means there would always be a log.
