### ISSUE TITLE
More flexibility on Remote driver host address

### ISSUE THREAD

**Issue by y3rsh** [pytest-dev/pytest-selenium#150]
Would you be open to a PR that would allow for a port value like -1 that would remove the colon and port number `:port` from the constructed url?   I desire to host a grid at an endpoint like `http://mygrid.mycompany.com/wd/hub`
https://github.com/pytest-dev/pytest-selenium/blob/2c40b5c395162f598ed02e7302d3ed4d71a0873b/pytest_selenium/drivers/remote.py#L12

**Comment by davehunt** [comment]
Would't that just default to port 80?

**Comment by davehunt** [comment]
Ah, the `resolve_ip` might be the important bit. Currently you can't set that using pytest-selenium. One thing you could try is to override the `driver_kwargs` fixture in your `contest.py` such as:

```python
@pytest.fixture
def driver_kwargs(driver_kwargs):
    rc = RemoteConnection(driver_kwargs['command_executor'], resolve_ip=False)
    kwargs['command_executor'] = rc
    return kwargs
```

**Comment by y3rsh** [comment]
This is much better, I was hasty indeed.  Thank you for the help.  It seems to defaut to 80.
`pytest --driver Remote --host mygrid.net --port 80 -k test_cancel_button` works when the `resolve_ip=False` 🍰. 
### Added to my Conftest.py:
```python
@pytest.fixture
def driver_kwargs(driver_kwargs):
    rc = RemoteConnection(driver_kwargs['command_executor'], resolve_ip=False)
    driver_kwargs['command_executor'] = rc
    return driver_kwargs
```

**Comment by davehunt** [comment]
Great! Hopefully a future version of the Python client will default to not resolving the IP address so you won't need that hack.

**Comment by y3rsh** [comment]
improved:
```python
if 'command_executor' in driver_kwargs:
    rc = RemoteConnection(driver_kwargs['command_executor'], resolve_ip=False)
    driver_kwargs['command_executor'] = rc
return driver_kwargs
```

**Comment by navinislam** [comment]
@y3rsh just ran into this myself with a host listening on port 80. Thanks for the final solution!
