### ISSUE TITLE
[Question] How to run headless in grid network

### ISSUE THREAD

**Issue by rarelam** [pytest-dev/pytest-selenium#152]
Hi all,

Sorry for asking question which is not related to this page.

I would like to ask how can I add FF argument or Chrome options for headless when running in grid environment?

It is able to configure chrome option in run time in conftest.py?

**Comment by davehunt** [comment]
If you're using Selenium Grid then I'm not sure why you'd want to run the browsers in headless mode, but for Firefox you should be able to use something like:

```python
@pytest.fixture
def firefox_options(request, firefox_options):
    firefox_options.add_argument('--headless')
    return firefox_options
```

Alternatively, you can set the `MOZ_HEADLESS` environment variable on your nodes. For more assistance I would suggest asking in the [Selenium users group](https://groups.google.com/forum/#!forum/selenium-users)
