### ISSUE TITLE
Error with pytest at command line

### ISSUE THREAD

**Issue by ORESoftware** [pytest-dev/pytest-selenium#154]
I was following the instructions in the docs, I have this:

```python
def test_example(selenium):
    selenium.get('http://www.example.com')
```

when I run this at the command line:

```terminal
(venv) $ pytest --driver Firefox
usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov --cov-report term-missing
  inifile: /Users/alexamil/WebstormProjects/oresoftware/sumanjs/sce/projects/python-basic/setup.cfg
  rootdir: /Users/alexamil/WebstormProjects/oresoftware/sumanjs/sce/projects/python-basic
```

do you know what that error is about? I think it has to do with these lines in my setup.cfg file:

```
addopts =
    --cov python_basic --cov-report term-missing
    --verbose
```

**Comment by davehunt** [comment]
As you suspect, this error is related to the options included in your `setup.cfg` file. The `--cov` and `--cov-report` arguments are provided by the [pytest-cov](https://pypi.python.org/pypi/pytest-cov/) plugin. You could either install that plugin, or remove these options from your configuration file, depending on whether or not you want code coverage reports. I hope this helps, however I'll close this issue, as it's unlrelated to the pytest-selenium plugin.

**Comment by ORESoftware** [comment]
thanks, I am new to python, I guess that would be

`pip3 install cov cov-report`

?

**Comment by BeyondEvil** [comment]
@ORESoftware Try `pip3 install pytest-cov`

**Comment by ORESoftware** [comment]
thanks looks good

**Comment by nikhilteja91** [comment]
> @ORESoftware Try `pip3 install pytest-cov`

yes it worked. thanks.
