### ISSUE TITLE
How to init virtual display before browser started?

### ISSUE THREAD

**Issue by TimurNurlygayanov** [pytest-dev/pytest-selenium#157]
Hi there,

my code:

```
    import pytest
    from pyvirtualdisplay import Display

    @pytest.fixture(scope="function")
    def web_browser(request, selenium):

        display = Display(visible=False, size=(1500, 1100))
        display.start()

        selenium.set_window_size(1400, 1000)

        # Return browser instance to test case:
        yield selenium

        selenium.quit()
        display.stop
```

I'm starting the tests in this way:

>     pytest -m functional -n 20 --alluredir=allure-results --driver Firefox --driver-path /tests/firefox

And all tests failed, in browser logs I can see the following error:

> cat /tmp/pytest-of-jenkins/pytest-115/popen-gw15/test_check_filters_False_None_0/driver.log
> 1522736525745	geckodriver	INFO	geckodriver 0.20.0
> 1522736525751	geckodriver	INFO	Listening on 127.0.0.1:59513
> 1522736526750	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.piZfMmr1aQct"
> Error: no DISPLAY environment variable specified

So, how can I start virtual display BEFORE pytest-selenium will try to start browser?
(I need to start several virtual displays - one display for each pytest thread)

**Comment by TimurNurlygayanov** [comment]
Found the workaround by myself:

```
import pytest
from pyvirtualdisplay import Display

@pytest.fixture(scope="session")
def display(request):
    display = Display(visible=False, size=(1500, 1100))
    display.start()

    yield display

    display.stop()

@pytest.fixture(scope="function")
def web_browser(request, selenium, display):
    selenium.set_window_size(1400, 1000)

    # Return browser instance to test case:
    yield selenium

    selenium.quit()

```

**Comment by davehunt** [comment]
Your solution appears to be starting only one virtual display, as your `display` fixture is session scoped. Also, you can simply call your `web_browser` fixture `selenium`, and hijack the existing fixture. Note that you can also run Firefox and Chrome headless if you didn't want to manage virtual displays.
