### ISSUE TITLE
goog:chromeOptions from capabilities json are ignored when remote driver is used

### ISSUE THREAD

**Issue by darkensk** [pytest-dev/pytest-selenium#160]
I want to run my tests using a remote driver in headless chrome browser. I'm using pytest-variables to pass capabilities.json as capabilities for the driver but the browser is not being run in headless mode (chrome window is opened every time). 

I think the json is in a correct format as it is working when I use json with selenium driver directly. That's why I started suspecting that  the issue is in pytest-selenium. 

While I was going through the code I found that in "capabilities" fixture inside pytest_selenium/pytest_selenium.py before the block handling remote driver class(from line 59 to line 72) the goog:chromeOptions are in the capabilities variable but after the block they are removed  from capabilities. 

Im trying to understand the "if" block on pytest_selenium/pytest_selenium.py:70: 

https://github.com/pytest-dev/pytest-selenium/blob/171321caed510f6b35108d743eea4b733207f177/pytest_selenium/pytest_selenium.py#L70-L71

for example when CHROME is the browser both key and options are set resulting in all([key, options]) returning "True" and thus executing the capabilities.setdefault... What I don't understand is what is it supposed to do? Right now it rewrites the capabilities that are loaded from the json with defaults. (as we see in the "capabilities" after the block). Shouldn't it work the other way around and combine the default values with the capabilities provided in the json? Am I missing something or is there something wrong in my setup? 

**Run command:**
`polka$ pytest ./tests/test_login.py --driver=Remote --variables=./capabilities_chrome.json`

**Platform and pytest plugins:**
- platform darwin -- Python 3.6.1, pytest-3.4.1, py-1.5.2, pluggy-0.6.0
- plugins: xdist-1.22.2, variables-1.7.1, selenium-1.11.4, metadata-1.6.0, html-1.16.1, forked-0.2, base-url-1.4.1

**Contents of capabilities_chrome.json:**
`{
  "capabilities": {
    "browserName": "chrome",
    "platform": "Mac",
    "goog:chromeOptions": {
      "args": [
        "headless"
      ]
    }
  }
}`

**Before the block, capabilities are:**
`"{'browserName': 'chrome', 'platform': 'Mac', 'goog:chromeOptions': {'args': ['headless']}}"`

**After the block, capabilities are:** 
`"{'browserName': 'chrome', 'platform': 'Mac', 'goog:chromeOptions': {'args': [], 'extensions': []}}"`

**Comment by davehunt** [comment]
This does indeed look like a bug. I think this is because we're using `update` to set the `goog:chromeOptions` key, instead of updating the values within that key. We should probably use a similar merge technique as pytest-variables implements here: https://github.com/pytest-dev/pytest-variables/blob/master/pytest_variables/plugin.py#L48-L66. Would you be interested in working on a fix? It might be a good idea to first see if you can write a failing test.

**Comment by BeyondEvil** [comment]
@davehunt  Let me know if @darkensk doesn't step up to the challenge! I'll take a look at it if he doesn't. 👍

**Comment by darkensk** [comment]
@BeyondEvil @davehunt I'm interested in working on a fix. I'll try to write the failing test first.

**Comment by BeyondEvil** [comment]
Any progress on this @darkensk do you need any pointers or help? 😃

**Comment by darkensk** [comment]
Sorry @BeyondEvil I was really busy at work lately. I've went through your current test suite to figure out how it's done and I've tried to write a failing test for the issue. Could you take a look at the commit https://github.com/darkensk/pytest-selenium/commit/7ee81b342d8901a5e890c3b92630342d29702c4d ? I could not find a better place to put it in but I'm open for suggestions, I'll start working on the merge technique @davehunt mentioned now.

**Comment by darkensk** [comment]
I've attempted to merge the capabilities following the pytest-variables example. You can check it here: https://github.com/darkensk/pytest-selenium/commit/de753b1f31dcecb01ea52a9b4a80048126ac8e51 I've kept it as a function and I've added logic for combining lists as well.  

It works, but one thing I'm concerned about is the "key" variable is not used at all now, could this potentially cause problems for users using old selenium and "chromeOptions" instead of "goog:chromeOptions"? On the other hand maybe we don't need that at all and the whole capabilities fixture could be changed (simplified)?

Please take a look and I'll be waiting for your feedback.

**Comment by BeyondEvil** [comment]
I took a quick look at the failing test and it seems to do what it is supposed to @darkensk 

Looking at the merge strategy however, there's something that is bothering me, but I can't quite put my finger on it... The code looks fine, and I'm sure it does what it's supposed to. But I have this feeling that it's over the top for what we _actually_ need/want.
But since I can't articulate my feelings - let's just ignore them for now, lol :)

I've added some comments to the merge function.

**Comment by darkensk** [comment]
@BeyondEvil I think you might be right that it is over the top. 

How about we stop thinking about the "big" merge for a second and go back to the original code:

https://github.com/pytest-dev/pytest-selenium/blob/171321caed510f6b35108d743eea4b733207f177/pytest_selenium/pytest_selenium.py#L70-L71

if we would change the L71 to:
`options.setdefault(key, {}).update(capabilities.get(key, {}))`
and set capabilities as options? It looks like it actually does what it is supposed to do and combines it nicely. Please take a look at an example here: https://repl.it/repls/AvariciousAngryCpu

**Comment by davehunt** [comment]
@darkensk @BeyondEvil I hope you don't mind that I've pushed a potential fix for this, but I needed to work through it to understand the problem better. I don't think my fix is much different from the one already proposed. Please take a look and let me know if it's working, or if I've missed something. Unfortunately merging two dictionaries isn't easy when you don't know what each key will contain, and you might want a different merge strategy for each. I suspect there are edge cases that my fix misses, but as the options are pretty basic, we should hopefully be okay. You can see my fix here: https://github.com/davehunt/pytest-selenium/commit/2de2e1a9e55a888002a097a9a72b46a777f4653a

**Comment by davehunt** [comment]
> Since pytest-selenium requires pytest-variables, should we put the "enhanced" merge code there and then just import the function in pytest-selenium?

There's a risk this would introduce issues in pytest-variables.. I'd like to keep the merge code there as basic as possible unless there are specific issues with it affecting users of that plugin.

> Afaict the code that darkensk has written should work just as well as the _merge in pytest-variables for the "simpler" config case.
> 
> It just seems silly to have almost identical pieces of code in two places.

You're probably right, but it's not a lot of code, and I'd prefer not to introduce the risk.

**Comment by darkensk** [comment]
@davehunt I don't mind at all. I appreciate the experience and that I was given a chance to try. I like the way you implemented it in the fix and from the testing I've done it does what I was expecting from the fix.

**Comment by davehunt** [comment]
Thanks @darkensk. I've merged the fix. I'd like to revisit a couple of other outstanding issues, but hope to release a new version soon.
