### ISSUE TITLE
DeprecationWarning: use service_log_path instead of log_path

### ISSUE THREAD

**Issue by edmorley** [pytest-dev/pytest-selenium#179]
Hi!

In the new v3.14.0 release of the Python selenium package, a new deprecation warning has been added, which is currently triggered by pytest-selenium:
```
...
    def driver(request, driver_class, driver_kwargs):
        """Returns a WebDriver instance based on options and capabilities"""
>       driver = driver_class(**driver_kwargs)
../../../venv/lib/python2.7/site-packages/pytest_selenium/pytest_selenium.py:154: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
...
    def __init__(self, firefox_profile=None, firefox_binary=None,
                 timeout=30, capabilities=None, proxy=None,
                 executable_path="geckodriver", options=None,
                 service_log_path="geckodriver.log", firefox_options=None,
                 service_args=None, desired_capabilities=None, log_path=None):
...
        if log_path:
>           warnings.warn('use service_log_path instead of log_path', DeprecationWarning)
E           DeprecationWarning: use service_log_path instead of log_path
../../../venv/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py:104: DeprecationWarning
```

See:
https://github.com/SeleniumHQ/selenium/pull/5979
https://travis-ci.org/mozilla/treeherder/jobs/411325051#L947

**Comment by davehunt** [comment]
Thanks @edmorley! Would you like to tackle this @BeyondEvil? We'd need to make sure we use `service_log_path` consistently, and depend on version >= 3.14.0 of the selenium package. I also think it would be good to pick up these deprecation warnings ourselves, so it would be good to treat them as failures when running our tests.

**Comment by BeyondEvil** [comment]
On it @davehunt 

> I also think it would be good to pick up these deprecation warnings ourselves, so it would be good to treat them as failures when running our tests.

You mean generally? If a test sees a warning (that is not explicitly expected) we fail the test?

**Comment by BeyondEvil** [comment]
PR ready in #180
