### ISSUE TITLE
Vulnerability fix in 1.14.0 (2018-08-23)

### ISSUE THREAD

**Issue by Jwomers** [pytest-dev/pytest-selenium#186]
Hi!

I maintain the pyup.io vulnerability database. I noticed in your latest changelog for 1.14.0: "Move Sauce Labs credentials to capabilities instead of URL" - What is the impact of this vulnerability, should I be notifying my users to upgrade to 1.14.0 for security reasons?

Thanks!

**Comment by BeyondEvil** [comment]
Closing this issue since there's been 13 days without any activity. Please feel free to re-open if you thing the issue hasn't been addressed properly @Jwomers

**Comment by Jwomers** [comment]
@davehunt @BeyondEvil thanks :)
