### ISSUE TITLE
Possibility of reusing browser session across different tests

### ISSUE THREAD

**Issue by kkarolk** [pytest-dev/pytest-selenium#187]
My use case involves logging in to the application, unfortunately it takes pretty long time. It would be a nice feature if I could reuse browser session across all my test cases, so I could login before and save some time of execution. Maybe the feature is there already but I browsed through the docs and couldn't find it.

**Comment by BeyondEvil** [comment]
Hi @kkarolk !

This question comes to us from time to time.
I would suggest you read here: #176 

With that said, maybe there's a different approach you can take to speed up logging in to your application.

Is it done thru the UI everytime?

**Comment by BeyondEvil** [comment]
Closing this issue since there's been three days without a response. Please feel free to reopen if you feel the issue hasn't been addressed sufficiently @kkarolk
