### ISSUE TITLE
Change browser for specific test

### ISSUE THREAD

**Issue by rgrzesk** [pytest-dev/pytest-selenium#189]
Is it possible to have different browser running within one test suite? What I mean is - running one test suite with setup, eg. --driver firefox, but for one test I would like to use Chrome.
I was trying to override option 'driver', but it doesn't allow me to do so.
Ideally it would be good to have that on test level, but it could also work as a fixture.

**Comment by BeyondEvil** [comment]
@rgrzesk Try this:

```
@pytest.fixture
def driver_class(request, driver_class):
    from selenium import webdriver

    if request.node.get_closest_marker('chrome'):
        request.config.option.driver = 'chrome'
        return webdriver.Chrome
    return driver_class


@pytest.fixture
def driver(request, driver_class, driver_kwargs):
    driver = driver_class(**driver_kwargs)
    request.node._driver = driver

    yield driver

    driver.quit()
```

Mark your test with `@pytest.mark.chrome`

Obviously, you can change the code so that it can take any browser.

**Comment by rgrzesk** [comment]
That's a good one :) Thanks!
But there are two problems with that:
1. Works only for local browsers - it overrides option '--driver' which doesn't work for Remote drivers
2. It overrides the driver for next tests as well - once you set the new browser it stays for next - for this one of course solution can be done by saving command line in separated object and setting always if browser is None

**Comment by BeyondEvil** [comment]
@rgrzesk 
1. Yes, for it to work with remote browsers you need to override capabilities.
2. Yes, you can change it to a yielding fixture, so that it reverses the changes made to `request.config.option.driver = browser.args[0]`

**Comment by rgrzesk** [comment]
1. How to override capabilities? Do you mean to override the whole method?
2. Sure, but the question is rather here is there any other place where the initial browser name is stored?

Other thing - `.get_closest_marker` doesn't exist, I have used `get_marker`

**Comment by rgrzesk** [comment]
1. Like that:
`pytest -s --driver Remote --host SeGrid --port 4444 --capability browserName chrome ./tests/folder`

`get_marker` - sure thing, I was using pytest3.3.2 ;)

**Comment by BeyondEvil** [comment]
@rgrzesk 

Then you also need to override the session_capabilities fixture.

**Comment by BeyondEvil** [comment]
Did you resolve this issue @rgrzesk ?

**Comment by BeyondEvil** [comment]
Closing this as stale.
