### ISSUE TITLE
Screenshots not showing up in report

### ISSUE THREAD

**Issue by NinjaSteph** [pytest-dev/pytest-selenium#196]
I must be missing something, but I can't seem to get screenshots to show up in my report on failure. Here is my conftest.py file:
```
from datetime import datetime
from py.xml import html
import pytest
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from stored_values.common_values import base_url
from pages.signup_page import SignupPage

options = Options()
# Set to false when debugging locally
options.set_headless(headless=True)

# Set up the driver
@pytest.fixture
def driver(request):
    driver = webdriver.Firefox(options=options)
    yield driver

    def close_browser():
        driver.quit()

    request.addfinalizer(close_browser)

# Add fixtures for pages
@pytest.fixture()
def SignupPageObject(driver):
    page = SignupPage(driver, root_uri=base_url)
    page.load()
    return page

# Additional content for pytest results
@pytest.mark.optionalhook
def pytest_html_results_table_header(cells):
    cells.insert(2, html.th('Description'))
    cells.insert(1, html.th('Time', class_='sortable time', col='time'))

@pytest.mark.optionalhook
def pytest_html_results_table_row(report, cells):
    cells.insert(2, html.td(report.description))
    cells.insert(1, html.td(datetime.utcnow(), class_='col-time'))

@pytest.mark.hookwrapper
def pytest_runtest_makereport(item, call):
    outcome = yield
    report = outcome.get_result()
    report.description = str(item.function.__doc__)
```

And here is the test it's running to trigger a failure:
```
from stored_values.common_values import get_users, password

class TestSignup:
    users = get_users()

    def test_signup(self, SignupPageObject):
        SignupPageObject.signup(password, **self.users[0])
        assert False
```

And here's my report that's missing the screenshot: 
![screen shot 2018-10-03 at 8 08 22 pm](https://user-images.githubusercontent.com/579696/46446082-442a5d80-c748-11e8-9bbf-80afe7fca87a.png)

Could someone give me a hand?

**Comment by davehunt** [comment]
You don't appear to be using the pytest-selenium plugin. The plugin provides a `driver` fixture, which sets up and tears down a Selenium session based on your configuration options. If you do have the plugin installed, then you're effectively disabling it by replacing this driver fixture: https://github.com/pytest-dev/pytest-selenium/blob/cdd1b07ccf09b97a792e0440ce990ca2513e5ec8/pytest_selenium/pytest_selenium.py#L187-L203

Note in particular this line: https://github.com/pytest-dev/pytest-selenium/blob/cdd1b07ccf09b97a792e0440ce990ca2513e5ec8/pytest_selenium/pytest_selenium.py#L201

This adds a `_driver` property to the node, which is accessed when generating the report: https://github.com/pytest-dev/pytest-selenium/blob/cdd1b07ccf09b97a792e0440ce990ca2513e5ec8/pytest_selenium/pytest_selenium.py#L245

The screenshot can only be gathered if we have access to an active Selenium session. Please see [the documentation](https://pytest-selenium.readthedocs.io/en/latest/user_guide.html) for more details on how to use this plugin.

**Comment by NinjaSteph** [comment]
Ah I see. I had written that code before installing `pytest-selenium` and didn't realize I'd have to change my setup. Thanks for the quick response! I'll close this out
