### ISSUE TITLE
yield_fixture decorator is deprecated

### ISSUE THREAD

**Issue by BeyondEvil** [pytest-dev/pytest-selenium#198]
According to: https://docs.pytest.org/en/latest/yieldfixture.html

We should update pytest-selenium to only use `fixture` decorator.

Could there be any potential negative side effects to changing this? What happens if someone has an override? 🤔 @davehunt 

We already require pytest 3.0 or later.

**Comment by RonnyPfannschmidt** [comment]
it perfectly fine to do
