### ISSUE TITLE
Set default browser when —driver not specified

### ISSUE THREAD

**Issue by itaymelamed** [pytest-dev/pytest-selenium#199]
Use Case:
When I want to run a test through Pycharm Ide Play button, there is no driver specified so test fails.

**Comment by davehunt** [comment]
You can add options to your pytest configuration file. For example `setup.cfg` could contain:

```ini
[tool:pytest]
addopts = --driver=Firefox
```

You can also specify these options via the `PYTEST_ADDOPTS` environment variable. See https://docs.pytest.org/en/latest/customize.html#adding-default-options for more details.

**Comment by BeyondEvil** [comment]
@itaymelamed Also, under `Run > Edit Configurations` you can set something called "Additional Arguments"
<img width="579" alt="screen shot 2018-10-10 at 00 53 40" src="https://user-images.githubusercontent.com/15611634/46703344-f8cfed80-cc26-11e8-81ec-78105c453d79.png">

**Comment by BeyondEvil** [comment]
Closing this as it seems resolved. Please feel free to reopen if that's not the case @itaymelamed  😊
