### ISSUE TITLE
Most Elegant Way to have Multiple Browser Configs In one test ?

### ISSUE THREAD

**Issue by thomascrha** [pytest-dev/pytest-selenium#203]
I'm having trouble trying to integrate your pytest-selenium into my testing suite. What I want to do is utilise the firefox and chrome options fixtures when initialising each driver but I want them to both run when I use the selenium directive. That is if I had this test:

```
def test_site(selenium):
    selenium.get('http://python.org')
    assert 'Python' in browser.title
``` 

It would be run on both Chrome and Firefox. What I got currently - minus all the added config and such (currently done using JSON config files) is this :

```
import pytest
from selenium import webdriver
 
BROWSERS = {
    'firefox': webdriver.Firefox,
    'chrome': webdriver.Chrome,
}
 
@pytest.fixture(scope='session',params=BROWSERS.keys())
def driver(request):
    browser = BROWSERS[request.param]()
 
    request.addfinalizer(lambda *args: browser.quit())
 
    return browser
```

I want todo something similar with what is already there - I had a look a this ticket also and tried to modify it with no luck

https://github.com/pytest-dev/pytest-selenium/issues/189

**Comment by BeyondEvil** [comment]
Hi @thomascrha 

Could you tell us a little bit more about the use-case? What is it you're trying to achieve?

Cheers

**Comment by BeyondEvil** [comment]
Is this run using a CI system?

Why I ask is because this looks like a case of overengineering.

Instead of trying to shoe-horn in running multiple browsers _within_ the test framework, why not take a step back and let the surrounding infrastructure (CI) handle it?

Perhaps anecdotal, but that's how we run it. It's less complex, we can use the tools out-of-the-box and it's only marginally slower. Given the overhead of running UI tests, I would even argue the extra time is negligible.

@thomascrha

**Comment by davehunt** [comment]
You could probably create a parameterised fixture that would provide a driver based on the configuration options. I think I even had something working in the past while playing around. That said, we just run multiple invocations like @BeyondEvil suggests in his comment.

**Comment by thomascrha** [comment]
Yeah I think this may be the best options and utilise my CI better. Thanks for the help guys.

**Comment by tbradley-sans** [comment]
I know this is closed and I can sorta understand why. But there is what I think is a valid use case for specifying multiple browsers in the same session, and that is to use the built-in PyTest test reporting (--html=./reports/testreport.html) to generate a single report that shows how all browsers did (pass/fail) on the test run.

Besides, the underlying WebDriver is designed to support specifying multiple browsers to be used, like this Python/WebDriver example shows (without pytest-selenium):

https://stackoverflow.com/a/22669648/2562745

**Comment by BeyondEvil** [comment]
> I know this is closed and I can sorta understand why. But there is what I think is a valid use case for specifying multiple browsers in the same session, and that is to use the built-in PyTest test reporting (--html=./reports/testreport.html) to generate a single report that shows how all browsers did (pass/fail) on the test run.

From what I know about pytest-html, I don't think that would be supported out of the box. But maybe I am wrong @RibeiroAna ?

> Besides, the underlying WebDriver is designed to support specifying multiple browsers to be used, like this Python/WebDriver example shows (without pytest-selenium):
> 
> https://stackoverflow.com/a/22669648/2562745

Strictly speaking, that isn't WebDriver supporting multiple browsers. "ExperimentsWithCode" just creates a list of capabilities and then iterates over that list creating a _new_ WebDriver instance for each browser.

You could do the same with pytest-selenium. However, it wouldn't give you what you want as far as the html report goes.

**Comment by tbradley-sans** [comment]
Ah, you're right. Thanks for the explanation. I'm coming at this from Webdriver.io (a Node.js toolkit on top of the JS WebDriver library), and they support capabilities being a list. So I assumed that was a WebDriver thing, but I guess that's a feature they've added in their custom test runner. That said, I'm quite happy with pytest-selenium so far. It was so easy to connect my tests to BrowserStack.
