### ISSUE TITLE
Can't install [appium] module

### ISSUE THREAD

**Issue by ranaara** [pytest-dev/pytest-selenium#225]
Hey,

I read in the latest documenation that from now pytest-selenium should support Appium. I have seen you work around it in the repository but when I try to install it like you specify in the documentation (pip install pytest-selenium[appium]) I get the error: **pytest-selenium 1.16.0 does not provide the extra 'appium'**

Do we need to wait for another pypi release? When we can expect it?

**Comment by Dude-X** [comment]
We would need to release a new version before you can install appium as an
extra.
There is no timeline for when the next release will be cut. Hopefully we
can I address two outstanding issues before we release.

**Comment by ranaara** [comment]
That totally makes sense. Just wanted to double check if it's not problem on my side. 
Great work guys, patiently waiting for the release.
