### ISSUE TITLE
Please add examples how to use it with flask app

### ISSUE THREAD

**Issue by lioramilbaum** [pytest-dev/pytest-selenium#229]

**Comment by BeyondEvil** [comment]
Hi @lioramilbaum 

Not sure what you're asking for. Could you provide us with some more context?

**Comment by lioramilbaum** [comment]
I was hoping to see code samples of how this module is used for testing a python flask app

**Comment by BeyondEvil** [comment]
@lioramilbaum 

With the risk of me misunderstanding something, I would say that you wouldn't use this plugin to test Flask. If we're talking about unit or integration tests.

This plugin is used in conjunction with [Selenium (WebDriver)](https://selenium.dev/) to test web apps (frontend/UI). It's agnostic to whatever backend system delivers the app.

Hope that helps!
