### ISSUE TITLE
Setting firefox acceptInsecureCerts capability using firefox_options fixture

### ISSUE THREAD

**Issue by MarkJB** [pytest-dev/pytest-selenium#230]
I'm not having much luck trying to figure out how to get firefox to accept insecure certificates and would appreciate being pointed in the right direction. None of the examples (in the docs or in the related issues here) cover it. I'm running this via Selenium Grid (3.9.1) and fwiw chrome works with the chrome_options fixture and .add_argument('--ignore-certificate-errors')

I'm not sure what the difference is between a preference, an option, a capability or a profile with respect to firefox or which one I should be attempting to set. But was looking at the following:
https://selenium.dev/selenium/docs/api/py/webdriver_firefox/selenium.webdriver.firefox.options.html
https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/acceptInsecureCerts

This is where I'm at currently (with some previous attempts at guessing the syntax commented out) but it doesn't appear to have an affect:

`@pytest.fixture
def firefox_options(firefox_options):
    firefox_options.set_capability('accept_insecure_certs', True)
    #firefox_options.set_preference('acceptInsecureCerts', True)
    #firefox_profile.set_preference('accept_insecure_certs', True)
    #firefox_options.add_argument('-accept_insecure_certs')
    return firefox_options`

The set_capability line does appear to affect the options as I can see 'acceptInsecureCerts = True' in the object but tests still fail with InsecureCertificateException.

**Comment by BeyondEvil** [comment]
The [default](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/common/desired_capabilities.py#L52) for Firefox is to accept insecure certs.

What error message are you getting? Can you repro it locally?

**Comment by MarkJB** [comment]
Ok that is good to know.

It works locally. I wasn't sure if that was because I had already accepted the certificate or if the webdriver is creating a new profile.

When running remote via selenium grid I see the InsecureCertificateException

`E       selenium.common.exceptions.InsecureCertificateException: Message:

..\..\venvdbt\lib\site-packages\selenium\webdriver\remote\errorhandler.py:242: InsecureCertificateException`

**Comment by MarkJB** [comment]
Just checked and firefox is warning about the certificate locally so selenium is configuring it to accepting the certs by default locally.

**Comment by MarkJB** [comment]
With or without the firefox_options fixture setting 'acceptInsecureCerts', when running locally firefox_accepts the certs, but running remote it doesn't... not sure where to go from here, but will keep trying.

**Comment by BeyondEvil** [comment]
I might be wrong, but judging from the investigating you've done, I don't think the problem lies within the plugin.

I would raise this question with the good folks over at [Selenium](https://github.com/SeleniumHQ/selenium).

**Comment by MarkJB** [comment]
I think you are probably right. Closing this issue. Thanks for your help.

**Comment by BeyondEvil** [comment]
Please report back whatever the findings are. 🙏

**Comment by MarkJB** [comment]
Raise issue with Selenium: https://github.com/SeleniumHQ/selenium/issues/8038
