### ISSUE TITLE
Xdist starts with blank page

### ISSUE THREAD

**Issue by RuslanBM** [pytest-dev/pytest-selenium#232]
Hello. Please help me to figure out problem launch pytest selenium in parallel with xdsit. 
I have two firefox instance at docker and launch 2 independent test this way:
`pytest -k "crypto" -n2`
And gets an Error:
`selenium.common.exceptions.InvalidArgumentException: Message: Malformed URL: / is not a valid URL.`

My Pipfile:
```PyPOM==2.2.0
pytest==5.1.2
pytest-bdd==3.2.1
pytest-xdist==1.31.0
pytest-base-url==1.4.1
pytest-selenium==1.17.0

gcloud==0.18.3
firebase==3.0.1
python_jwt==3.2.4
sseclient-py==1.7
py-postgresql==1.2.1
requests-toolbelt==0.9.1
arrow==0.15.4
kombu==4.6.7
```

My pytest.ini
```
[pytest]
bdd_features_base_dir = tests
base_url = https://projectname.com
sensitive_url = https://projectname.com
addopts = --driver Remote
          --port 4444
          --capability browserName firefox
          --html tests/logs/report.html
          --cucumberjson=tests/uploads/cucumber.json
          --cucumberjson-expanded
          -v
filterwarnings =
    ignore::DeprecationWarning
markers =
    smoke: fast result
    crypto: add calculations
```
Here is track trace:

result = call_fixture_func(fixturefunc, request, kwargs)
../../.pyenv/versions/3.6.8/envs/projectname/lib/python3.6/site-packages/_pytest/fixtures.py:778: in call_fixture_func
    res = fixturefunc(**kwargs)
tests/functional/test_02_deposit_by_dash.py:20: in user_signed_in
    page_main.open()
../../.pyenv/versions/3.6.8/envs/projectname/lib/python3.6/site-packages/pypom/page.py:130: in open
    self.driver_adapter.open(self.seed_url)
../../.pyenv/versions/3.6.8/envs/projectname/lib/python3.6/site-packages/pypom/selenium_driver.py:48: in open
    self.driver.get(url)
../../.pyenv/versions/3.6.8/envs/projectname/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:333: in get
    self.execute(Command.GET, {'url': url})
../../.pyenv/versions/3.6.8/envs/projectname/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:321: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x10faa6f98>
response = {'status': 400, 'value': '{"value":{"error":"invalid argument","message":"Malformed URL: / is not a valid URL.","stack...dArgumentError@chrome://marionette/content/error.js:304:5\\nget@chrome://marionette/content/listener.js:1132:19\\n"}}'}
**E       selenium.common.exceptions.InvalidArgumentException: Message: Malformed URL: / is not a valid URL.**

It works without -n2: 
`pytest -k "crypto"`

<img width="1385" alt="Screenshot 2020-03-09 at 16 14 51" src="https://user-images.githubusercontent.com/54805270/76216432-a59a0a00-6221-11ea-87a6-7637bfe7079f.png">
<img width="1387" alt="Screenshot 2020-03-09 at 16 15 18" src="https://user-images.githubusercontent.com/54805270/76216461-ad59ae80-6221-11ea-8bd3-265dc41fd13c.png">

**Comment by BeyondEvil** [comment]
I'm fairly confident this is not a pytest-selenium issue.

Could you try to reproduce this by using selenium directly, without using pytest-selenium?

**Comment by BeyondEvil** [comment]
I can't reproduce this.

Here's a repo you can fork if you want to create a repo to show how to reproduce. https://github.com/BeyondEvil/pytest-playground

**Comment by RuslanBM** [comment]
> I can't reproduce this.
> 
> Here's a repo you can fork if you want to create a repo to show how to reproduce. https://github.com/BeyondEvil/pytest-playground

How exactly you run it? I got some errors:
```
_____________________________________________________________________ ERROR at setup of test_selenium1 _____________________________________________________________________
file /Users/ruslan.go/Projects/pytest-playground-master/tests/test_selenium.py, line 8
  def test_selenium1(driver):
E       fixture 'driver' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/ruslan.go/Projects/pytest-playground-master/tests/test_selenium.py:8```

**Comment by RuslanBM** [comment]
Looks like problem at pytest-base-url 1.4.1 plugin. https://pypi.org/project/pytest-base-url/ 
I replace in tests `page_main.open()` with `page_main.open_url('www.google.com')` and it brings to green result.
