### ISSUE TITLE
Test wont execute

### ISSUE THREAD

**Issue by lkkushan101** [pytest-dev/pytest-selenium#234]
platform win32 -- Python 3.5.0, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
driver: Chrome
sensitiveurl: .*
rootdir: C:\Users\user\PycharmProjects\PyTestSelenium
plugins: base-url-1.4.1, html-1.22.1, metadata-1.8.0, selenium-1.17.0, variables-1.9.0
collected 0 items                                                                                                                                                                           

When  I ran the test browser wont come up instead I get the above error....

**Comment by lkkushan101** [comment]
This is the script 
import pytest


def test_example(selenium):
    selenium.get('http://www.google.com')

**Comment by Dude-X** [comment]
There's no error or traceback posted.

**Comment by BeyondEvil** [comment]
> This is the script
> import pytest
> 
> def test_example(selenium):
> selenium.get('http://www.google.com')

Most likely the file containing the test script is not named [properly](https://docs.pytest.org/en/latest/goodpractices.html#conventions-for-python-test-discovery). @lkkushan101

**Comment by BeyondEvil** [comment]
Any progress @lkkushan101 ?

**Comment by Dude-X** [comment]
I will close this issue on July 6th if there's no response.

**Comment by BeyondEvil** [comment]
Feel free to reopen if not solved.
