### ISSUE TITLE
[Feature] Add edge_options fixture

### ISSUE THREAD

**Issue by PhilippSelenium** [pytest-dev/pytest-selenium#235]
In order to run the Edge Chromium driver (https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/edge/webdriver.py#L59). I need to be able to pass the options arg to the edge driver similar to firefox or chrome and I don't think that this is possible with the current state?

**Comment by BeyondEvil** [comment]
I think you're right, at a quick glance at least.

Are you up for adding this feature in a PR? @PhilippSelenium

**Comment by PhilippSelenium** [comment]
I looked into that and noticed that this is only available on the master branch and not yet released. But I will try to make a PR as soon as version 4.0 is released (Should not be that long they are already in alpha)

**Comment by BeyondEvil** [comment]
Fixed in #245

**Comment by BeyondEvil** [comment]
Fixed in #245
