### ISSUE TITLE
Error with pytest - Allure

### ISSUE THREAD

**Issue by katekoz** [pytest-dev/pytest-selenium#236]
Hello, Im having this problem after Allure Commandline installation.
When I try to run this command in terminal Im getting this problem:

![issue pytest](https://user-images.githubusercontent.com/33467825/79556093-e26ae380-80a0-11ea-9a65-f524fb2f2f69.png)

Any idea what this could be?
Ive already checked other related topics, and I installed 
pip install allure-pytest

not sure the screen will be visible so the error is like this:
(venv) C:\Users\Kasia\PycharmProjects\tutorial_selenium>pytest --alluredir=C:\Users\Kasia\PycharmProjects\tutorial_selenium\report
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --alluredir=C:\Users\Kasia\PycharmProjects\tutorial_selenium\report
  inifile: None
  rootdir: C:\Users\Kasia\PycharmProjects\tutorial_selenium

**Comment by RonnyPfannschmidt** [comment]
the output of `pytest -h` should help to gather some more details

**Comment by BeyondEvil** [comment]
Ping @katekoz

**Comment by BeyondEvil** [comment]
Closing this since we haven't heard anything and it looks like `allure-pytest` is [deprecated](https://github.com/allure-framework/allure-pytest)

**Comment by BeyondEvil** [comment]
Closing this since we haven't heard anything and it looks like `allure-pytest` is [deprecated](https://github.com/allure-framework/allure-pytest)
