### ISSUE TITLE
reports missing <img> tags for screenshots

### ISSUE THREAD

**Issue by anothermattbrown** [pytest-dev/pytest-selenium#237]
The generated report html is missing the `<img>` tag for screenshots. 

Example test:
``` 
def test_foo(selenium):
    selenium.get('http://google.com')
    assert False
```

command:
```
$ pytest --driver chrome --driver-path path/to/chromedriver test.py --html report.html
```

The report shows a blank square instead of an image:
<img width="1673" alt="Screen Shot 2020-05-12 at 12 46 50 PM" src="https://user-images.githubusercontent.com/15133240/81738852-36be7480-944f-11ea-89e4-28e849918414.png">

In the inspector, there's an empty `<a>` tag:
<img width="815" alt="Screen Shot 2020-05-12 at 12 47 18 PM" src="https://user-images.githubusercontent.com/15133240/81738726-024ab880-944f-11ea-873a-41c914d054fe.png">

The link in the `<a>` tag goes to the (expected) screenshot on disk.

I can't tell if this is a problem with `pytest-selenium`, `pytest-html`, or something else. Any help would be appreciated.

**Comment by dhalperi** [comment]
I can shed some light.

1. Here's the code in `pytest-selenium` that gathers the screenshot and passes it to `pytest-html`: https://github.com/pytest-dev/pytest-selenium/blob/d1d4ff6f7817cc5c3b178e7524cda5b70ee06e4a/pytest_selenium/pytest_selenium.py#L291-L300

2. Here's the code in `pytest-html` that handles that call and generates the report: https://github.com/pytest-dev/pytest-html/blob/103c849cac7b8e0dbaf0a151a541a8c085fb008e/pytest_html/plugin.py#L293-L323

The flow is as follows:

* pytest-selenium [collects only base64 image bytes](https://github.com/pytest-dev/pytest-selenium/blob/d1d4ff6f7817cc5c3b178e7524cda5b70ee06e4a/pytest_selenium/pytest_selenium.py#L293), and passes that [directly to `pytest-html.extras.image`](https://github.com/pytest-dev/pytest-selenium/blob/d1d4ff6f7817cc5c3b178e7524cda5b70ee06e4a/pytest_selenium/pytest_selenium.py#L300).

2. The code in `pytest-html.extras.image`, however, only uses the [`img` code](https://github.com/pytest-dev/pytest-html/blob/103c849cac7b8e0dbaf0a151a541a8c085fb008e/pytest_html/plugin.py#L326) when it's passed a [file or URL for `content`](https://github.com/pytest-dev/pytest-html/blob/103c849cac7b8e0dbaf0a151a541a8c085fb008e/pytest_html/plugin.py#L312) or when the [entire report is self-contained](https://github.com/pytest-dev/pytest-html/blob/103c849cac7b8e0dbaf0a151a541a8c085fb008e/pytest_html/plugin.py#L316).

The code in `extras._make_media_html_div` that is actually used is the final case, where code there [makes an asset dynamically](https://github.com/pytest-dev/pytest-html/blob/103c849cac7b8e0dbaf0a151a541a8c085fb008e/pytest_html/plugin.py#L317-L322). In that case, the `base_extra_string` that contains the IMG tag is not used in generating the final HTML.

The fix could be in either place: `pytest-selenium` could create the asset before passing it in, or `pytest-html` could use the `img` tag even when it creates the asset. I haven't yet been able to determine which fix is the right one.

**Comment by dhalperi** [comment]
Okay, digging, it looks like this was an unintentional result of refactoring in `pytest-html`: https://github.com/pytest-dev/pytest-html/commit/588c41b33f2ca8884c65d3de6ccb4ade55a44bd2

Before that commit, the `img` tag was applied for created assets. That no longer happens in the refactored code.

**Comment by dhalperi** [comment]
Cross-linking to existing `pytest-html` issue: https://github.com/pytest-dev/pytest-html/issues/265

**Comment by anothermattbrown** [comment]
Thanks @dhalperi. For now, I confirmed that `--self-contained-html` is a work-around.

**Comment by BeyondEvil** [comment]
Hopefully in not a too distant future we'll release a new version of pytest-html, which will solve this issue.

**Comment by andreashetz** [comment]
Please fix it. Thanks

**Comment by anothermattbrown** [comment]
Fixed by https://github.com/pytest-dev/pytest-html/pull/298
