### ISSUE TITLE
Let's track changes with a basic CHANGELOG

### ISSUE THREAD

**Issue by Dude-X** [pytest-dev/pytest-selenium#242]
This project has light maintenance but as we are getting closer to a Selenium 4.0 beta, we should create a changelog to keep track of changes done for the convenience of our users.

**Comment by nicoddemus** [comment]
There's already a changelog in https://github.com/pytest-dev/pytest-selenium/blob/master/docs/news.rst, or do you mean something else?

**Comment by Dude-X** [comment]
Ah yes, there is a changelog. I did try looking for it yesterday but somehow overlooked this file. Thanks.
