### ISSUE TITLE
webdriver timeout exception

### ISSUE THREAD

**Issue by suva180** [pytest-dev/pytest-selenium#258]
When the tests are run thr' the pipeline we get timeout exceptions often. We have added sleep
We use python . We import these 
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

We use wait time as below:
time.sleep(2)
    WebDriverWait(self.driver, 5).until(EC.presence_of_element_located((By.CSS_SELECTOR, "loginname" )))

Whats the best way to handle timeout exceptions?

Thank you

**Comment by BeyondEvil** [comment]
I would ask this question in the Selenium slack channel. 👍
