### ISSUE TITLE
Chromium support

### ISSUE THREAD

**Issue by GergelyKalmar** [pytest-dev/pytest-selenium#263]
I'm not sure if Chromium is supported at the moment – I could only see Chrome when selecting a driver. If it isn't, would it be possible to add support for Chromium too?

**Comment by dosas** [comment]
Do you have a download link to browser and driver?

**Comment by GergelyKalmar** [comment]
If I understand the [documentation](https://www.selenium.dev/documentation/en/webdriver/driver_requirements/#chromiumchrome) correctly the driver should be the same, and as for Chromium itself I'm using the snap version on Ubuntu. I think the only difference should be that in this case a `chromium` webdriver class should be instantiated instead of the `chrome` one (see [docs](https://www.selenium.dev/selenium/docs/api/py/api.html#webdriver-chromium)).

**Comment by Dude-X** [comment]
Selenium python v4 has a Chromium class to support both Chrome and Edge but even with v3, Chromium should work since the Service class should look for chromium. Otherwise, set up the service or options class to use a different path to the browser.

**Comment by GergelyKalmar** [comment]
So I tried adding this to `conftest.py`:
```python
import pytest


@pytest.fixture
def chrome_options(chrome_options):
    chrome_options.binary_location = '/snap/bin/chromium'
    return chrome_options
```

However, this didn't work:
```python
def test_homepage(live_server, selenium):
    selenium.get(f'{live_server.url}')
```

Chromium does open but the URL bar shows `data:,` instead of the right URL.

It works fine with Chrome though. Should I be doing something differently?

**Comment by GergelyKalmar** [comment]
The URL is something along the lines of `http://localhost:54891`, with the port changing between runs (`live_server` being a `pytest-django` fixture).

**Comment by GergelyKalmar** [comment]
Never mind – it seems that I was able to make it all work after some more tweaking. Thank you for the support!
