### ISSUE TITLE
HTTPS support for remote driver

### ISSUE THREAD

**Issue by platonoff-dev** [pytest-dev/pytest-selenium#266]
It's impossible now to provide protocol in `selenium-host` argument. 

https://github.com/pytest-dev/pytest-selenium/blob/a91b1f5e0252bb10654516f3bb73598b11a72e22/pytest_selenium/drivers/remote.py#L12 
Now `http://` hardcoded in source code, but If I need `https://` it's imposible 😞

**Comment by platonoff-dev** [comment]
I think, I know what to do with this issue. If there is no refusal I will work on fixing this issue.

**Comment by isaulv** [comment]
Hmmm, in light of changes coming to Selenium 4 and how firefox handles profiles, maybe this needs a rewrite.

**Comment by platonoff-dev** [comment]
Ohhh this issue lost in my list of issues 😅, and I forgot about it.
I think this issue can be separated on two: quick fix a problem with url, rewriting for coming changes from selenium 4.

**Comment by platonoff-dev** [comment]
> Hmmm, in light of changes coming to Selenium 4 and how firefox handles profiles, maybe this needs a rewrite.

What kind of changes in selenium 4 did you talk about?

**Comment by BeyondEvil** [comment]
> Ohhh this issue lost in my list of issues 😅, and I forgot about it.
> I think this issue can be separated on two: quick fix a problem with url, rewriting for coming changes from selenium 4.

I'm happy to review any PRs @platonoff-dev !
