### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by mickyJNST** [pytest-dev/pytest-selenium#287]
There hasn't been much recent activity in the way of releases, PRs, responses to issues, etc. Given this, is it reasonable to assume this project is basically done? Anyone know of alternatives to this project?

**Comment by isaulv** [comment]
This project isn't dead, but given my current responsibilities with work and family it is difficult to address issues. That being said, I may have a selenium project at work that I can get myself acquainted with the changes in Selenium 4.0 and thus update the project.

One major change though is to change the test suite for the project from travis to circle ci or GitHub actions. I think this is done but I have to get familiar with these changes.

**Comment by BeyondEvil** [comment]
Like @isaulv said, it's not dead.

I'm going to try and revive it in the next couple of weeks.

**Comment by mickyJNST** [comment]
Thanks @isaulv & @BeyondEvil - good to hear!
