### ISSUE TITLE
Add support to pytest>=7.2.0

### ISSUE THREAD

**Issue by sp-luciano-chinke** [pytest-dev/pytest-selenium#305]
Hi everyone! 

In order to avoid dependency in py package and remove the [security issue ](https://github.com/pytest-dev/py/issues/287) that affects that package, it would be nice that pytest-selenium supported pytest versions above 7.2.0.

**Comment by wolny-wojciech** [comment]
yes, please

**Comment by BeyondEvil** [comment]
The code for this is in master, I'm working on some other fixes before I cut a release.

**Comment by gt-fm-4562** [comment]
Hi, when the support for ^7.0.0 will begin?

**Comment by RonnyPfannschmidt** [comment]
We have information that @BeyondEvil is currently subject to a personal bus factor, i may be able to do a release this weekend

**Comment by erkin98** [comment]
> We have information that @BeyondEvil is currently subject to a personal bus factor, i may be able to do a release this weekend

how is it going with release?

**Comment by wolny-wojciech** [comment]
> > We have information that @BeyondEvil is currently subject to a personal bus factor, i may be able to do a release this weekend
> 
> how is it going with release?

So how is it going? @BeyondEvil

**Comment by BeyondEvil** [comment]
I've been tied up with finalizing the rebuild and re-release of pytest-html unfortunately.

I'm planning on release a new RC (for pytest-html) before EOW. If the feedback from that is positive and there are no P1 bugs, I can cut a proper 4.0 release.

After that I'm turning my attention towards this plugin.

Thank you for your patience! Apologies for any inconvenice this is causing. 🙇

**Comment by jesselathamdev** [comment]
Hi there, wondering if it's still on the radar to get a new cut of pytest-selenium released which supports pytest 7.2+?

Cheers and keep up the great work.

**Comment by BeyondEvil** [comment]
Thanks for the reminder! 🙏🏼

I can’t make any promises, but I’ll do my vest to cut a release before EOW.
