### ISSUE TITLE
TypeError when upgrading to selenium 4.10

### ISSUE THREAD

**Issue by melisabok** [pytest-dev/pytest-selenium#315]
When upgrading to selenium 4.10, I'm getting the following error:

```
TypeError: WebDriver.__init__() got an unexpected keyword argument 'service_log_path'
```

It seems that selenium [removed](https://github.com/SeleniumHQ/selenium/commit/9f5801c82fb3be3d5850707c46c3f8176e3ccd8e) the parameter service_log_path that is being used [here](https://github.com/pytest-dev/pytest-selenium/blob/master/src/pytest_selenium/pytest_selenium.py#L166).

It is there another way to pytest-selenium without having this error?

**Comment by BeyondEvil** [comment]
Yes, use the previous version of selenium.

**Comment by andreymal** [comment]
I got a similar error with another keyword

```
TypeError: WebDriver.__init__() got an unexpected keyword argument 'desired_capabilities'
```

(downgrading to Selenium 4.9.1 fixes it)
