### ISSUE TITLE
`Screenshot` doesn't match with `HTML`

### ISSUE THREAD

**Issue by changchiyou** [pytest-dev/pytest-selenium#327]
I except that `Screenshot` will display the innerText of `recognized-texts` in `HTML`:

```html
<p id="recognized-texts">2024-02-18 00:17:20 [00059baiden]<br>2024-02-18 00:18:22 [005657obama]<br></p>
```

However, it is not behaving as expected:

|Screenshot|HTML|
|-|-|
|<img src="https://github.com/pytest-dev/pytest-selenium/assets/46549482/6bc3fe53-f1cc-4047-b1f2-7fae008ec551" alt="drawing" width="400"/>|<img src="https://github.com/pytest-dev/pytest-selenium/assets/46549482/3afb6dc7-c4f4-4900-a42c-80f2b2acecce" alt="drawing" width="400"/>|

Should I manually insert a `time.sleep()` in the code section found at

https://github.com/pytest-dev/pytest-selenium/blob/c5be64bc8fffef5f4639a375619b614472f561ab/src/pytest_selenium/pytest_selenium.py#L297-L306

, or is there any existing argument that I may have overlooked?

**Comment by changchiyou** [comment]
After I manually insert a `time.sleep()` and rerun the pytest, it works.

|Edit|Result|
|-|-|
|<img src="https://github.com/pytest-dev/pytest-selenium/assets/46549482/5f0c981a-2b42-484e-976f-13dc2286aa39" alt="drawing" width="400"/>|<img src="https://github.com/pytest-dev/pytest-selenium/assets/46549482/44ac5a84-c1ea-4673-b692-96454a645241" alt="drawing" width="400"/>|

**Comment by changchiyou** [comment]
NVM, adding `time.sleep()` right after `selenium.get()` can easily solve the problem:

```python
@pytest.mark.webtest
@pytest.mark.usefixtures("live_server")
@pytest.mark.parametrize(*p_args(args={"RECOGNIZE": True, "TEMP_FEATURES": True}), **p_kwargs()) # type: ignore
def test_RealtimeRecognition_create_flask(create_tmp_folders_files, ini_config_setting_v2, selenium):
    selenium.get(url_for("index", _external=True))
    sleep(1) # here
```

**Comment by RonnyPfannschmidt** [comment]
the correct way is to wait for expected elements to appear, random sleeps are fragile

**Comment by RonnyPfannschmidt** [comment]
(in an more complex scenario dynamic element appearance is potentially load/performance dependent, random sleeps entually fail unless you make them painfully long)

**Comment by changchiyou** [comment]
According to https://github.com/pytest-dev/pytest-selenium/issues/327#issuecomment-1951046257, I replace `time.sleep(1)` with:

```python
recognized_texts = [
  "2024-02-18 00:17:20 [00059]",
  "2024-02-18 00:18:22 [05657]",
],
```

```python
    while sum([1 for recognized_text in recognized_texts if recognized_text in selenium.page_source]) \
          != len(recognized_texts):
        ... # complete full logics here or use for loop instead for time limitation
```

**Comment by RonnyPfannschmidt** [comment]
Use all instead of sum

**Comment by changchiyou** [comment]
According to https://github.com/pytest-dev/pytest-selenium/issues/327#issuecomment-1951317590, I adjust the code from:

```python
    while sum([1 for recognized_text in recognized_texts if recognized_text in selenium.page_source]) \
          != len(recognized_texts):
        ... # complete full logics here or use for loop instead for time limitation
```

to:

```python
    while not all([recognized_text in selenium.page_source for recognized_text in recognized_texts]):
        ... # complete full logics here or use for loop instead for time limitation
```
