### ISSUE TITLE
Add a recipe to conda-forge

### ISSUE THREAD

**Issue by birdsarah** [pytest-dev/pytest-selenium#70]
I mainly use conda to install pytest-selenium.

I currently build my own binaries and upload them to mine and the bokeh conda channels.

I'd like to propose adding a recipe to conda-forge - https://conda-forge.github.io/

I'm happy to take the lead on this, but obviously wanted to get comments first.

**Comment by nicoddemus** [comment]
FWIW I find it a great idea. I've recently added recipes for [pytest-mock](https://github.com/conda-forge/pytest-mock-feedstock), [pytest-qt](https://github.com/conda-forge/pytest-qt-feedstock) and [pytest-faulthandler](https://github.com/conda-forge/pytest-faulthandler-feedstock) and it was a breeze! 

I suggest you to lead this and add me and @davehunt as maintainers (if @davehunt is OK with it, of course).

**Comment by davehunt** [comment]
Works for me!

**Comment by birdsarah** [comment]
https://github.com/conda-forge/staged-recipes/pull/2075

Finally got around to this.

I also have recipes queued up for pytest-html and pytest-base-url but I thought I'd see how this one goes first.

**Comment by nicoddemus** [comment]
Thanks @birdsarah. Unfortunately this might not be the best moment, as conda-forge is facing a major CircleCI outage (responsible for building the linux packages). 😞

**Comment by birdsarah** [comment]
it'll get there eventually!

**Comment by nicoddemus** [comment]
Oh sure sure, didn't mean to discourage you at all, just commenting how things are at the moment. 😁

**Comment by davehunt** [comment]
Thanks @birdsarah & @nicoddemus!

**Comment by BeyondEvil** [comment]
ping @birdsarah @nicoddemus What's the status of this? :)

**Comment by birdsarah** [comment]
I may have some time next week. Feel free to bug me about it.

**Comment by birdsarah** [comment]
Thanks! I'm going to finish this by the end of pycon if nothing else.

**Comment by birdsarah** [comment]
Progress is being made. `pytest-metadata` `pytest-base-url` and `pytest-variables` are in. `pytest-html` is next, then should be able to rerun `pytest-selenium`

**Comment by birdsarah** [comment]
pytest-selenium pr is running again https://github.com/conda-forge/staged-recipes/pull/2075 - hopefully will pass this time.

**Comment by birdsarah** [comment]
Woot - this is done :D 

```sh
(testing) $ conda install pytest-selenium
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/sbird/miniconda3/envs/testing

The following NEW packages will be INSTALLED:

    py:               1.4.33-py35_0
    pytest:           3.1.1-py35_0
    pytest-base-url:  1.3.0-py35_0  conda-forge
    pytest-html:      1.14.2-py35_0 conda-forge
    pytest-metadata:  1.5.0-py35_0  conda-forge
    pytest-selenium:  1.10.0-py35_0 conda-forge
    pytest-variables: 1.6.1-py35_0  conda-forge
    selenium:         3.4.2-py35_0  conda-forge

Proceed ([y]/n)?
```

**Comment by nicoddemus** [comment]
:+1:
