### ISSUE TITLE
When used with Appium I can not add a screenshot of the report.html

### ISSUE THREAD

**Issue by mehmetboraezer** [pytest-dev/pytest-selenium#73]
Hello everyone,

I am trying using this the plugin with Appium Python Library and Selenium Grid. But I have a question. I am trying add a screenshot etc. in report.html like robot framework but I can't do it. I can take screenshot anywhere of code except error.

My running code:

```
py.test --driver Remote --capability platform ANDROID --html=report.html ~/testdatafile/tests/
```

At the end I want to do exactly that: 
![Image of Report](https://cloud.githubusercontent.com/assets/122800/11951695/f371b926-a88a-11e5-91c2-499166776bd3.png)

**Comment by davehunt** [comment]
Could you provide a stacktrace or console output? The screenshot code isn't in pytest-selenium, so I suspect an issue in Selenium, Appium, or Android. When you say "I can take screenshot anywhere of code" how are you taking this screenshot?

**Comment by davehunt** [comment]
Closing due to lack of further details.
