### ISSUE TITLE
What's the best way for pytest selenium test in long operation objects

### ISSUE THREAD

**Issue by HackToday** [pytest-dev/pytest-selenium#76]
Hi All,

I am using the pytest selenium and test one software, right now, I found a problem.

in unittest python, it always have setUpClass and tearDownClass, while in py.test it all changed to fixture,

I am confused by one issue, my requirements like below:

I have a selenium test case: create one app, and start app, stop app, and suspend app
For above operation, I have like blew:

```
   Class APPOPS:

       def start_app(self):
           ...

      def stop_app(self):
         ...
```

Both those need app existed first, so I need to create app for all those tests, I want to make start_app and stop_app share the same app, which can reduce test time(let's forget test random run case first).

for setUpClass, it is easy for me

for fixture it always in separate file, like `conftest.py`, the problem is that is it good way to do create app logic in `confest.py` file?  I didn't think it is good to do that. As create app is so special, it should not be put in conftest.py general like that

Do you suggest other better ways ?  Thanks

**Comment by davehunt** [comment]
It sounds like this is a general pytest question. I would recommend the [pytest-dev mailing list](https://mail.python.org/mailman/listinfo/pytest-dev) or #pylib on irc.freenode.net IRC channel. Thanks.

**Comment by HackToday** [comment]
@davehunt  it would better append some thoughts here and close this if you have some suggestions for this question. Thanks.
