### ISSUE TITLE
INTERNALERROR: KeyError: 'startdir'

### ISSUE THREAD

**Issue by jondelmil** [pytest-dev/pytest-selenium#78]
Hi, I'm using py.test and django. After installing `pytest-selenium`, I got the following error.

Can anyone shed some light on this?
```
$ py.test
Test session starts (platform: darwin, Python 3.5.2, pytest 3.0.2, pytest-sugar 0.7.1)
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/jon/.virtualenvs/webapp/lib/python3.5/site-packages/_pytest/main.py", line 94, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/Users/jon/.virtualenvs/webapp/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/jon/.virtualenvs/webapp/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/jon/.virtualenvs/webapp/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/Users/jon/.virtualenvs/webapp/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/jon/.virtualenvs/webapp/lib/python3.5/site-packages/pytest_sugar.py", line 217, in pytest_sessionstart
INTERNALERROR>     lines = self.config.hook.pytest_report_header(config=self.config)
INTERNALERROR>   File "/Users/jon/.virtualenvs/webapp/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/jon/.virtualenvs/webapp/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/jon/.virtualenvs/webapp/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/Users/jon/.virtualenvs/webapp/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 593, in execute
INTERNALERROR>     args = [all_kwargs[argname] for argname in hook_impl.argnames]
INTERNALERROR>   File "/Users/jon/.virtualenvs/webapp/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 593, in <listcomp>
INTERNALERROR>     args = [all_kwargs[argname] for argname in hook_impl.argnames]
INTERNALERROR> KeyError: 'startdir'
```
I tested this with both selenium 3.0.0b2 and 2.53.6 -- same error. When I uninstalled `pytest-selenium` the error went away.

[Here's an example project](https://github.com/jondelmil/example), sorry it's so big but it's the quickest way to get where I am now.

To reproduce, `pip install -r requirements/test.txt && pip install -r requirements/local.txt`, then `py.test`

I also had to properly space line 49 in `/Users/jon/.virtualenvs/example/lib/python3.5/site-packages/selenium/webdriver/safari/webdriver.py` to fall under the if statement, per [this commit](https://github.com/SeleniumHQ/selenium/commit/055325c09d783b6b6c9cbdeaa0828384048b0222).

**Comment by nicoddemus** [comment]
The problem is actually in pytest-sugar. Just spotted this on the traceback:

```
INTERNALERROR>   File "/Users/jon/.virtualenvs/webapp/lib/python3.5/site-packages/pytest_sugar.py", line 217, in pytest_sessionstart
INTERNALERROR>     lines = self.config.hook.pytest_report_header(config=self.config)
```

`pytest_report_header` received a `startdir` parameter in [2.3.0](https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst#230):

> pytest_report_header now receives a "startdir" so that you can use startdir.bestrelpath(yourpath) to show nice relative path

 and pytest-sugar doesn't [honor that](https://github.com/Frozenball/pytest-sugar/blob/master/pytest_sugar.py#L217).

It should be simple to reproduce it. Create two files in an empty directory:

```python
# conftest.py
def pytest_report_header(startdir):
    return 'hello: ' + startdir

# test_foo.py
def test():
    pass
```

And execute it with pytest-sugar active. It should give the exact same error and in fact I'm not sure `test_foo.py` is really needed to reproduce this.

Can you please confirm this? And if that's the case, report the issue at the [pytest-sugar repository](https://github.com/Frozenball/pytest-sugar/)?

**Comment by jondelmil** [comment]
@nicoddemus You're correct, I confirmed with your suggestions. Tests only passed once pytest-sugar was removed. [Here's the commit](https://github.com/jondelmil/example/commit/5c6bd6517997373ef0cb032013bc6523f3c82294) if you're curious.

**Comment by jondelmil** [comment]
Done, thanks! Would you mind explaining how you got to see the stack trace deeper than mine?

**Comment by nicoddemus** [comment]
You mean this?

```
INTERNALERROR>   File "/Users/jon/.virtualenvs/webapp/lib/python3.5/site-packages/pytest_sugar.py", line 217, in pytest_sessionstart
INTERNALERROR>     lines = self.config.hook.pytest_report_header(config=self.config)
```

This was on the traceback you posted...

**Comment by jondelmil** [comment]
Oops! Somehow skipped that since it was indented. Thanks again!!

**Comment by nicoddemus** [comment]
No worries!
