### ISSUE TITLE
pytest-selenium can not work with Firefox geckodriver

### ISSUE THREAD

**Issue by HackToday** [pytest-dev/pytest-selenium#81]
As Firefox support geckodriver,  as listed in 
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver  

## How to reproduce that

```
py.test --base-url http://<myapp-ip>:8081 --host selenium-host --port 4444  --driver Remote --capability browserName firefox  --capability marionette true mytest
```

## The error looks like

```
  @pytest.fixture
    def selenium(request):
        """Returns a WebDriver instance based on options and capabilities"""
        driver_type = request.config.getoption('driver')
        if driver_type is None:
            raise pytest.UsageError('--driver must be specified')
    
        driver_fixture = '{0}_driver'.format(driver_type.lower())
>       driver = request.getfuncargvalue(driver_fixture)

/usr/lib/python2.7/site-packages/pytest_selenium/pytest_selenium.py:82: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python2.7/site-packages/pytest_selenium/drivers/remote.py:41: in remote_driver
    browser_profile=firefox_profile)
/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:90: in __init__
    self.start_session(desired_capabilities, browser_profile)
/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:177: in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:236: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x160ea90>
response = {'status': 500, 'value': '{"state":"unhandled error","sessionId":null,"hCode":536781276,"value":{"localizedMessage":"T...3,"class":"java.lang.IllegalStateException","screen":null},"class":"org.openqa.selenium.remote.Response","status":13}'}

    def check_response(self, response):
        """
            Checks that a JSON response from the WebDriver does not have an error.
    
            :Args:
             - response - The JSON response from the WebDriver server as a dictionary
               object.
    
            :Raises: If the response contains an error message.
            """
        status = response.get('status', None)
        if status is None or status == ErrorCode.SUCCESS:
            return
    
        value = None
        message = response.get("message", "")
        screen = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, basestring):
                import json
                try:
                    value = json.loads(value_json)
                    status = value.get('error', None)
                    if status is None:
                        status = value["status"]
                        message = value["value"]
                        if not isinstance(message, basestring):
                            value = message
                            try:
                                message = message['message']
                            except TypeError:
                                message = None
                    else:
                        message = value.get('message', None)
                except ValueError:
                    pass
    
        exception_class = ErrorInResponseException
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = WebDriverException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = WebDriverException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        else:
            exception_class = WebDriverException
        if value == '' or value is None:
            value = response['value']
        if isinstance(value, basestring):
            if exception_class == ErrorInResponseException:
                raise exception_class(response, value)
            raise exception_class(value)
        if message == "" and 'message' in value:
            message = value['message']
    
        screen = None
        if 'screen' in value:
            screen = value['screen']
    
        stacktrace = None
        if 'stackTrace' in value and value['stackTrace']:
            stacktrace = []
            try:
                for frame in value['stackTrace']:
                    line = self._value_or_default(frame, 'lineNumber', '')
                    file = self._value_or_default(frame, 'fileName', '<anonymous>')
                    if line:
                        file = "%s:%s" % (file, line)
                    meth = self._value_or_default(frame, 'methodName', '<anonymous>')
                    if 'className' in frame:
                        meth = "%s.%s" % (frame['className'], meth)
                    msg = "    at %s (%s)"
                    msg = msg % (meth, file)
                    stacktrace.append(msg)
            except TypeError:
                pass
        if exception_class == ErrorInResponseException:
            raise exception_class(response, message)
        elif exception_class == UnexpectedAlertPresentException and 'alert' in value:
            raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
>       raise exception_class(message, screen, stacktrace)
E       WebDriverException: Message: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/jgraham/wires. The latest version can be downloaded from https://github.com/jgraham/wires
E       Stacktrace:
E           at com.google.common.base.Preconditions.checkState (Preconditions.java:199)
E           at org.openqa.selenium.remote.service.DriverService.findExecutable (DriverService.java:109)
E           at org.openqa.selenium.firefox.GeckoDriverService.access$0 (GeckoDriverService.java:1)
E           at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable (GeckoDriverService.java:80)
E           at org.openqa.selenium.remote.service.DriverService$Builder.build (DriverService.java:296)
E           at org.openqa.selenium.firefox.MarionetteDriver.setupService (MarionetteDriver.java:94)
E           at org.openqa.selenium.firefox.MarionetteDriver.<init> (MarionetteDriver.java:71)
E           at org.openqa.selenium.firefox.MarionetteDriver.<init> (MarionetteDriver.java:49)
E           at sun.reflect.NativeConstructorAccessorImpl.newInstance0 (NativeConstructorAccessorImpl.java:-2)
E           at sun.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:62)
E           at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
E           at java.lang.reflect.Constructor.newInstance (Constructor.java:423)
E           at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor (FirefoxDriverProvider.java:91)
E           at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance (FirefoxDriverProvider.java:66)
E           at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance (DefaultDriverFactory.java:60)
E           at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call (DefaultSession.java:222)
E           at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call (DefaultSession.java:1)
E           at java.util.concurrent.FutureTask.run (FutureTask.java:266)
E           at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:176)
E           at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
E           at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
E           at java.lang.Thread.run (Thread.java:745)

```

**Comment by davehunt** [comment]
pytest-selenium is compatible with GeckoDriver 0.10 and Firefox 48 (current release, though you don't state which version you're using). You exception appears to be that Selenium is unable to locate the GeckoDriver binary. You can either make sure this is in your path (it must be named either `wires` or `geckodriver` depending on the version of Selenium in use), or you can use the `--driver-path` command line option from pytest-selenium to pass the full path to the binary.

Please reopen if you still suspect an issue with pytest-selenium, however Selenium issues can be found [here](https://github.com/SeleniumHQ/selenium/issues) and GeckoDriver issues can be found [here](https://github.com/mozilla/geckodriver/issues). You may also find the Selenium [user forum](https://groups.google.com/forum/#!forum/selenium-users) a good place to get help with this.

**Comment by HackToday** [comment]
@davehunt  I did not get  pytest-selenium support version with Firefox. I used Firefox 45.0.2,  I did not think only have to use Firefox 48. Could you give official pytest-selenium link for your above comments ?

**Comment by HackToday** [comment]
And besides, the GeckoDriver is located on /usr/bin. I have followed the link
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver  as I said.

And also pytest-selenium not have clear instructions or command how to use with GeckoDriver.
I think if above comments not address, we should open this issue.

**Comment by HackToday** [comment]
I have used  

```
 --driver Remote --capability browserName firefox  --capability marionette true --driver-path=/usr/bin/geckodriver
```

Still get same issue, so I will reopen it as above comments not clear.  Thanks

**Comment by HackToday** [comment]
Hi @davehunt  as the issue was closed not by myself, so I can not reopen it. Please help leave your comments  here.  Thanks

**Comment by davehunt** [comment]
> I did not get pytest-selenium support version with Firefox. I used Firefox 45.0.2, I did not think only have to use Firefox 48.

GeckoDriver and Marionette support Firefox 48 and onwards. See https://github.com/mozilla/geckodriver#supported-firefoxen for more details.

> And besides, the GeckoDriver is located on /usr/bin

Your exception is "The path to the driver executable must be set by the webdriver.gecko.driver". Have you tried doing this on your remote node? Note that geckodriver must be on the path on your remote node, not your host (unless they are the same).

> pytest-selenium not have clear instructions or command how to use with GeckoDriver

I'll take care of updating the documentation soon (unless someone submits a pull request before I get to it). This will be very similar to the Google Chrome or Internet Explorer documentation that simply states that for Firefox 48 you will need to download the GeckoDriver binary and make sure it is in the path.

> --driver Remote --capability browserName firefox  --capability marionette true --driver-path=/usr/bin/geckodriver

This is clearly not your full command line, however from this I see that you're using a remote WebDriver instance but not specifying a host or port. This means pytest-selenium will be expecting a Selenium server instance running locally. Specifying the marionette capability is fine, although in 3.0beta this is not needed. The driver path looks good assuming this is the correct path to the GeckoDriver binary. Also please check that the file is executable.

If you're still having issues please provide your full command line and stack trace.

**Comment by HackToday** [comment]
hi  @davehunt  

1> As above link I gave, 
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver 

the the GeckoDriver is located on /usr/bin is on remote node.

2> The full command run is:

py.test --base-url http://<myapp-ip>:8081 --host selenium-host --port 4444  --driver Remote --capability browserName firefox  --capability marionette true   --driver-path=/usr/bin/geckodriver  mytest

The host or port not have any issue, as I have successfully run on that without geckodriver.

So my question is from above strace, it seems pytest-selenium still not work if enable geckodriver

**Comment by davehunt** [comment]
> So my question is from above strace, it seems pytest-selenium still not work if enable geckodriver

I have successfully run pytest-selenium with GeckoDriver, and at Mozilla we're even doing this using Selenium Grid running version 3.0b2. Your stack trace suggests that the remote Selenium server is unable to find the GeckoDriver binary.

I'm happy to help you to resolve this, but the issue is not with pytest-selenium. Have you tried setting `webdriver.gecko.driver` as suggested by the stack trace? The trace also suggests that you're using a version of Selenium that's looking for a binary named 'wires' so please make sure you have the correct filename. You could also try the latest beta of Selenium 3.0 to see if that's working.

**Comment by HackToday** [comment]
OK  @davehunt  From you comments, it seems you used selenium 3.0 not 2.53.
Is it such case ?

**Comment by davehunt** [comment]
I have successfully used both, but would certainly recommend using 3.0 beta for both the server and client, especially if you're using the latest version of GeckoDriver. Unfortunately there's a lot of ongoing work, so for best results use the latest versions of everything. In the future this will calm down.

Alternatively, you can for now stick with Selenium 2.x but do not attempt to use anything later than Firefox 47.0.1.

**Comment by HackToday** [comment]
Thanks @davehunt  But the said point is that,

I used selenium 2.53.1 and Firefox 45.0.2, and pytest-selenium.
I tried latest geckodriver.

Besides try that 3.0-beta.  I really do not know what geckodriver can work with above environments.


If you did run successfully with both cases.  Could you give your versions for 2.x ?  I  want to make sure if there is something wrong with the version or not

**Comment by HackToday** [comment]
And cc @lukeis Do you know which selenium version can work with Geckodriver ?

**Comment by davehunt** [comment]
I would not recommend using GeckoDriver for any Firefox version before 48. I know that the latest version of GeckoDriver (0.10) actually requires Selenium 3.0 beta due to a change in the way Selenium launches the binary. If you want to use GeckoDriver I strongly encourage you to use the latest available (3.0) Selenium client/server.

I wonder, if Selenium 2.53.x and Firefox 45.x are working for you, what is your motivation to upgrade, or for what reason would you only want to upgrade some of these components?

**Comment by HackToday** [comment]
Hi  @davehunt  The reason is that,

In our selenium test, we found  sometimes (maybe 1 in 10 times) hit such random failure:

```
The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.
```
And I googled following link:

https://snakeycode.wordpress.com/category/selenium/

which suggest use GeckoDriver  can solve such issue. 

BTW, I opened in https://github.com/pytest-dev/pytest-selenium/issues/80  and you closed that :0

**Comment by HackToday** [comment]
After more experiments, I found that selenium 2.53.* can work with  GeckoDriver 0.8.0
https://github.com/mozilla/geckodriver/releases/download/v0.8.0/geckodriver-0.8.0-linux64.gz

It can not work with latest geckodriver.


Also Firefox 48 have bugs which can not work with Select drop down. So I would not use Firefox 48 with selenium 3.0.*

**Comment by HackToday** [comment]
Hi  @davehunt Sorry, It still can not work.  As I tried above without use  `marionette`. I am thinking selenium not support Geckodriver in 2.53.

**Comment by davehunt** [comment]
> use GeckoDriver can solve such issue

It's more that the issue is not going to be fixed in Selenium (assuming it's a Selenium issue) because all efforts have switched to GeckoDriver. That issue may not exist when using GeckoDriver, but you'll almost certainly hit other issues while the WebDriver spec and GeckoDriver are still in development.

> It can not work with latest geckodriver.

You'll probably find 0.9.0 may also work, but you're correct that latest won't work with 2.x because of a change in the command line options for GeckoDriver that requires a Selenium 3.x.

> Also Firefox 48 have bugs which can not work with Select drop down

That's an example of the ongoing effort to implement WebDriver spec compliant implementation in GeckoDriver/Marionette. You can [see the status here](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status) and fixes typically land in our nightly builds, and if safe we uplift them to our next release branch. This means that the best support for now will be in prereleases of Firefox.

> Sorry, It still can not work. As I tried above without use `marionette`

I don't understand this comment as it directly contradicts your earlier remark. Unless you mean you're trying to use Selenium 2.x without the `marionette` capability? If so, this is not expected to work, as in 2.x the default is to not use GeckoDriver/Marionette, and the capability must be set to enable it. In 3.x the default has been switched to use GeckoDriver/Marionette.

**Comment by HackToday** [comment]
the last comment is that, selenium 2.53.x can work with old Firefox Driver

if you try to use GeckoDriver, which means use this in command line `--capability browserName firefox --capability marionette true`  It would still fail. so it means, 2.53.x still not work with GeckoDriver Firefox 45

**Comment by davehunt** [comment]
Right, GeckoDriver does not support Firefox 45.

**Comment by RonnyPfannschmidt** [comment]
@davehunt is there any support matrix somewhere, i feel its quite unfortunate that api users like @HackToday spend time and time again askging for details and contributors such as yourself answering and answering, if all thats really needed is a list of supported combinations

**Comment by davehunt** [comment]
@RonnyPfannschmidt there's not, and I feel maintaining one might be challenging. If you want to use Firefox 48+ you ***must*** use GeckoDriver, which is in alpha and the latest version (0.10.0) ***requires*** the latest beta release of Selenium 3.0. This becomes complex because you might have some success using (for example) Firefox 45 with GeckoDriver 0.9.0 and Selenium 2.53.x.

**Comment by RonnyPfannschmidt** [comment]
ouch ^^ unfortunate
but its like 3 dimensions of variation, i wonder if someone can automate generating a reasonably accurate list of working capabilities at each combination

**Comment by davehunt** [comment]
It's four dimensions if you include the Selenium remote server component. I strongly suspect Firefox version will be the main driving factor. Therefore:

Firefox 45-47: Use Selenium 2.53.x
Firefox 48+: Use latest GeckoDriver and Selenium 3 prereleases

When Selenium 3 is released, you will be able to use it with Firefox 45-47 by specifying a capability of `marionette` with a value of `false`.

While other combinations might work, they're not recommended and more importantly not supported, so you're unlikely to get assistance.
