### ISSUE TITLE
Explicit wait is not wait the amount of time required

### ISSUE THREAD

**Issue by rikirenz** [pytest-dev/pytest-selenium#84]
Browser Version:
OS Version:

I have a dynamic page written with jQuery. My page changes a lot and I need to wait in order to give time to the page to render some elements that are necessary for test a specific procedure.

What's happening and even if I am using these lines of code:

```
WebDriverWait(selenium, 30).until(EC.text_to_be_present_in_element((By.ID, "topnav"), 'My account'))
selenium.find_element_by_id("user-info").click()
```

In the second line when I try to click on the element that should be present on the page, the code is raising a Not Visible Exception. 
I have seen that sometimes this can happen but it is a very unpredictable behaviour because sometimes it works and sometimes it does not work.

Do you have any ideas?

**Comment by davehunt** [comment]
@rikirenz this is a Selenium question, and isn't an issue with pytest-selenium. I would suggest asking this on the [Selenium users group](https://groups.google.com/forum/#!forum/selenium-users). You probably just want to create an explicit wait for the 'user-info' element to be visible.
