### ISSUE TITLE
Specify driver and driver-path in ini file

### ISSUE THREAD

**Issue by yourcelf** [pytest-dev/pytest-selenium#89]
It's cumbersome to always have to keep type `--driver` and `--driver-path` on the command line, or to have to add yet another wrapper script to fire up py.test with these options specified.

Is there a reason these couldn't be added as ini file options in addition to command line options?

**Comment by nicoddemus** [comment]
You can use pytest's builtin `addopts` for that:

```ini
[pytest]
addopts = --driver=Firefox
```

**Comment by yourcelf** [comment]
Oh perfect, thank you!

**Comment by nicoddemus** [comment]
👍
