### ISSUE TITLE
How to specify log level setting for geckodriver in pytest

### ISSUE THREAD

**Issue by HackToday** [pytest-dev/pytest-selenium#92]
Hi, recently, I have found issue in geckodriver when run with pytest-selenium.
However, geckodriver developer need trace-level log setting.

While run with pytest. how to set options like this below:

```
https://github.com/mozilla/geckodriver#log-object

{"moz:firefoxOptions": {"log": {"level": "trace"}}}
```

Which can help me to provide trace logs to geckodriver developers to debug issue.

Thanks

**Comment by HackToday** [comment]
Refer here https://github.com/mozilla/geckodriver#log-object


and @davehunt  do you know how to set that ?  Thanks

**Comment by davehunt** [comment]
You can override the `firefox_options` fixture to change the log level:

```python
@pytest.fixture
def firefox_options(firefox_options):
    firefox_options.log.level = 'trace'
    return firefox_options
```

**Comment by HackToday** [comment]
Thanks @davehunt 

One point I am not sure how pytest picks up the setting above?

For example, tests/conftest.py, I have something like

```
 14 @pytest.fixture
 15 def selenium(selenium):
 16     selenium.implicitly_wait(15)
 17     return selenium
``` 

In test, I could pass above to test 

```
 11     @pytest.mark.nondestructive
 12     def test_online_support_work(self, base_url, selenium, user):
               .....
```

But for `firefox_options`, how to pass it to test ? Or pass it through command line option ?  Could you give an example ?

**Comment by davehunt** [comment]
The `firefox_options` fixture is called indirectly by the `selenium` fixture when Firefox is in use. This means you only need to override this fixture by name, and you do not need to call it explicitly. If you wanted to, you could create your own command line argument in `conftest.py` that could be used to set the log level, but I don't provide this as a feature of pytest-selenium.

**Comment by HackToday** [comment]
Ok @davehunt  I will try the override ways and check if log setting works.  Thanks
