### ISSUE TITLE
Check additional environment variables for credentials

### ISSUE THREAD

**Issue by davehunt** [pytest-dev/pytest-selenium#96]
When using Jenkins declarative pipelines, credentials can be set as environment variables as follows:

```groovy
environment { 
    SAUCELABS = credentials('SAUCELABS') 
}
```

For credentials which are of type "Standard username and password", the environment variable specified will be set to `username:password` and two additional environment variables will be automatically be defined: `MYVARNAME_USR` and `MYVARNAME_PSW` respectively.

It would be convenient for pytest-selenium to therefore check `SAUCELABS_USR` and `SAUCELABS_PSW` for Sauce Labs, and similar for `BROWSERSTACK`, `TESTINGBOT`, and `CROSSBROWSERTESTING`.

See https://jenkins.io/doc/pipeline/tour/environment/ for more details.

**Comment by BeyondEvil** [comment]
I can probably do this at the same time as #107

**Comment by BeyondEvil** [comment]
ping @davehunt

**Comment by davehunt** [comment]
@BeyondEvil I've invited you to collaborate on the project so I can assign this to you. Please feel free to start work on this, however I'd prefer a separate pull request.
