### ISSUE TITLE
How to pass ['--ignore-ssl-errors=true', '--ssl-protocol=any'] to PhantomJS?

### ISSUE THREAD

**Issue by sontek** [pytest-dev/pytest-selenium#97]
Hey, I'm trying to migrate to `pytest-selenium` from my hand-rolled system and currently the only thing I'm missing is:

```
driver = webdriver.PhantomJS(service_args=['--ignore-ssl-errors=true', '--ssl-protocol=any'])
```

but I don't see anything in the docs on how to pass this through

**Comment by davehunt** [comment]
This isn't currently possible, but I don't think it would be too hard to add. Perhaps a `service_args` fixture in https://github.com/pytest-dev/pytest-selenium/blob/master/pytest_selenium/drivers/phantomjs.py, such as:

```python
import pytest

def driver_kwargs(capabilities, driver_path, service_args, **kwargs):
    kwargs = {'desired_capabilities': capabilities}
    if driver_path is not None:
        kwargs['executable_path'] = driver_path
    kwargs['service_args'] = service_args
    return kwargs

@pytest.fixture
def service_args():
    return []
```

With this, you could then override this fixture in `conftest.py` or similar:

```python
import pytest

@pytest.fixture
def service_args(request, service_args):
    service_args.extend(['--ignore-ssl-errors=true', '--ssl-protocol=any'])
    return service_args
```

Maybe we could even make this a generic fixture, but that would depend on `service_args` being a valid keyword argument for all of the drivers.

**Comment by sontek** [comment]
I would *love* to see this feature.  I just ran into the second need for it while porting my code over to this instead of my custom system.  When I want to debug phantom I need to do:

```
driver = webdriver.PhantomJS(service_args=["--remote-debugger-port=9000"])
```

**Comment by davehunt** [comment]
Would you be interested in working on the feature? I'd be happy to mentor you. Looking into it, it seems the following drivers support a `service_args` keyword argument:

* Chrome
* Opera
* PhantomJS

I'm fine with just adding support into https://github.com/pytest-dev/pytest-selenium/blob/master/pytest_selenium/drivers/phantomjs.py for now, and we can always add support for the other drivers later.

**Comment by sontek** [comment]
Yeah, I can give it a shot.  I don't have a lot time, moving to `pytest-selenium` is still just an experiment to see if it can handle everything I'm doing in my tests.  As long as this is the only thing missing I'll definitely contribute

**Comment by davehunt** [comment]
Great, I think this would be a pretty straight-forward change. If you're unable to get to it, I might pick it up myself if I get some time.

**Comment by davehunt** [comment]
@sontek I've created a `driver_args` fixture, documented here: http://pytest-selenium.readthedocs.io/en/latest/user_guide.html#id3. It will be in the next version of pytest-selenium, which I hope to release soon.
